"use client";

/**
 * Async and infinite-scroll option loading.
 *
 * ENGINE-OWNED. Everything here is transport-agnostic: the request is built by
 * `../transport/requestBuilder`, sent by whatever `OptionsTransport` is in
 * context, and cached by whatever `OptionsQueryAdapter` is in context. The
 * defaults are `fetch` + React state, so a bare install pulls in no HTTP or
 * data-fetching dependency at all.
 *
 * To use axios / react-query, supply them from your variant's `services.ts` /
 * `hooks.ts` through `FormTransportProvider` — do not edit this file.
 * See AI_AGENT_RULES § R-53 / § R-54.
 */
import { useCallback, useEffect, useMemo, useRef, useState } from "react";

import type { AsyncApiConfig, FieldOption } from "../types/types";
import { useFormTransport } from "../transport/context";
import { buildOptionsRequest, buildPaginationParams } from "../transport/requestBuilder";

// ─── Types ───

export type InfiniteOption = FieldOption;

export interface InfiniteOptionsResult {
  options: InfiniteOption[];
  hasMore: boolean;
  page: number;
}

/** Function signature for custom paginated fetch implementations */
export type FetchOptionsFunction = (
  searchTerm: string,
  page: number,
  pageSize: number
) => Promise<InfiniteOptionsResult>;

// ─── Helpers ───

/**
 * Safely retrieves a nested value from an object using a dot-separated path.
 * Returns the root object if path is empty.
 */
export function getByPath(obj: Record<string, unknown>, path: string): unknown {
  if (!path || path.trim() === "") return obj;
  return path.split(".").reduce<unknown>((acc, key) => {
    if (acc && typeof acc === "object" && key in (acc as Record<string, unknown>)) {
      return (acc as Record<string, unknown>)[key];
    }
    return undefined;
  }, obj);
}

/**
 * Maps a raw API response to an array of { label, value } options.
 * If dataPath is empty, assumes the response itself is the array.
 */
export function mapResponseToOptions(
  data: unknown,
  mapping: AsyncApiConfig["responseMapping"]
): InfiniteOption[] {
  const dataArray =
    !mapping.dataPath || mapping.dataPath.trim() === ""
      ? data
      : getByPath(data as Record<string, unknown>, mapping.dataPath);
  if (!Array.isArray(dataArray)) return [];
  return dataArray.map((item: Record<string, unknown>) => {
    const opt: InfiniteOption & { _raw?: Record<string, unknown> } = {
      label: String(item[mapping.labelKey] ?? ""),
      value: String(item[mapping.valueKey] ?? ""),
    };
    // Preserve extra keys for dependent field watchers
    if (mapping.extraKeys?.length) {
      const raw: Record<string, unknown> = {};
      for (const key of mapping.extraKeys) {
        raw[key] = item[key];
      }
      opt._raw = raw;
    }
    return opt;
  });
}

// ─── Async hook: one-time fetch on mount / when source changes ───

export interface UseAsyncOptionsProps {
  fetchOptions?: () => Promise<InfiniteOption[]>;
  apiConfig?: AsyncApiConfig;
  initialOptions?: InfiniteOption[];
}

/**
 * Fetches a flat list of options once when the component mounts (or when the source changes).
 */
export function useAsyncOptions({
  fetchOptions,
  apiConfig,
  initialOptions = [],
}: UseAsyncOptionsProps) {
  const { transport, adapter } = useFormTransport();
  const watchValue = apiConfig?._watchValue;
  const hasSource = !!fetchOptions || !!apiConfig?.url;

  const run = useCallback(
    async (signal?: AbortSignal): Promise<InfiniteOption[]> => {
      if (fetchOptions) return fetchOptions();
      if (apiConfig?.url) {
        try {
          const raw = await transport(buildOptionsRequest(apiConfig), signal);
          return mapResponseToOptions(raw, apiConfig.responseMapping);
        } catch {
          return [];
        }
      }
      return [];
    },
    [fetchOptions, apiConfig, transport],
  );

  const { data, isLoading, error } = adapter.useAsyncQuery({
    key: ["async-options", apiConfig?.url ?? "custom", watchValue ?? ""],
    enabled: hasSource,
    run,
  });

  const options = useMemo(() => {
    if (!hasSource) return initialOptions;
    return [...initialOptions, ...(data ?? [])];
  }, [hasSource, initialOptions, data]);

  const filterOptions = useCallback(
    (term: string) => {
      if (!term) return options;
      const lower = term.toLowerCase();
      return options.filter(
        (opt) =>
          opt.label.toLowerCase().includes(lower) ||
          opt.value.toLowerCase().includes(lower)
      );
    },
    [options]
  );

  return {
    options,
    isLoading: hasSource ? isLoading : false,
    error: error as Error | null,
    filterOptions,
  };
}

// ─── Infinite hook: paginated fetch + IntersectionObserver ───

interface UseInfiniteOptionsProps {
  fetchOptions?: FetchOptionsFunction;
  apiConfig?: AsyncApiConfig;
  pageSize?: number;
  debounceMs?: number;
  enabled?: boolean;
}

/**
 * Manages paginated, searchable option loading for infinite scroll fields.
 * Supports both page-based and offset-based pagination.
 */
export function useInfiniteOptions({
  fetchOptions,
  apiConfig,
  pageSize = 20,
  debounceMs = 300,
  enabled = true,
}: UseInfiniteOptionsProps) {
  const { transport, adapter } = useFormTransport();
  const [searchTerm, setSearchTerm] = useState("");
  const [debouncedTerm, setDebouncedTerm] = useState("");

  useEffect(() => {
    const timer = setTimeout(() => setDebouncedTerm(searchTerm), debounceMs);
    return () => clearTimeout(timer);
  }, [searchTerm, debounceMs]);

  const effectivePageSize = apiConfig?.pageSize ?? pageSize;
  const watchValue = apiConfig?._watchValue;

  const resolvedFetch = useMemo((): FetchOptionsFunction | null => {
    if (fetchOptions) return fetchOptions;
    if (!apiConfig?.url) return null;

    return async (search: string, page: number, size: number) => {
      const params = buildPaginationParams(apiConfig, search, page, size);

      try {
        const raw = await transport(buildOptionsRequest(apiConfig, params));
        const options = mapResponseToOptions(raw, apiConfig.responseMapping);

        let hasMore = false;
        if (apiConfig.hasMorePath) {
          const moreValue = getByPath(raw as Record<string, unknown>, apiConfig.hasMorePath);
          if (typeof moreValue === "boolean") {
            hasMore = moreValue;
          } else if (typeof moreValue === "number") {
            const loadedSoFar = page * size;
            hasMore = loadedSoFar < moreValue;
          }
        } else {
          hasMore = options.length >= size;
        }

        return { options, hasMore, page };
      } catch {
        return { options: [], hasMore: false, page };
      }
    };
  }, [fetchOptions, apiConfig, transport]);

  const cacheKey = debouncedTerm.toLowerCase() || "__all__";

  const run = useCallback(
    async (page: number): Promise<InfiniteOptionsResult> => {
      if (!resolvedFetch) return { options: [], hasMore: false, page: 1 };
      return resolvedFetch(debouncedTerm, page, effectivePageSize);
    },
    [resolvedFetch, debouncedTerm, effectivePageSize],
  );

  const { pages, isLoading, isFetchingNextPage, hasNextPage, fetchNextPage } =
    adapter.useInfiniteQuery({
      key: ["infinite-options", apiConfig?.url ?? "custom", watchValue ?? "", cacheKey],
      enabled: enabled && !!resolvedFetch,
      run,
    });

  const options = useMemo<InfiniteOption[]>(() => {
    const all = pages.flatMap((p) => p.options);
    return Array.from(new Map(all.map((o) => [o.value, o])).values());
  }, [pages]);

  const observerRef = useRef<IntersectionObserver | null>(null);
  const sentinelRef = useCallback(
    (node: HTMLDivElement | null) => {
      if (observerRef.current) observerRef.current.disconnect();
      if (!node) return;
      observerRef.current = new IntersectionObserver(
        (entries) => {
          if (entries[0]?.isIntersecting && hasNextPage && !isFetchingNextPage) {
            fetchNextPage();
          }
        },
        { threshold: 0.1 }
      );
      observerRef.current.observe(node);
    },
    [hasNextPage, isFetchingNextPage, fetchNextPage]
  );

  return {
    options,
    isLoading,
    isFetchingNextPage,
    hasMore: hasNextPage,
    searchTerm,
    setSearchTerm,
    sentinelRef,
  };
}
