/**
 * AUTO-GENERATED by scripts/build-dnd-registry.ts
 * DO NOT EDIT MANUALLY — run `npm run build:dnd-registry` to regenerate.
 */

export interface DndRegistryFile {
  name: string;
  path: string;
  code: string;
  language: "typescript" | "tsx" | "css";
  description: string;
}

export const dndRegistryGeneratedAt = "2026-05-15T06:55:28.029Z";

export const dndInstall = {
  "npmDependencies": [
    "react",
    "react-dom",
    "lucide-react",
    "clsx",
    "tailwind-merge"
  ],
  "npmDevDependencies": [],
  "uiComponents": [
    "utils"
  ]
} as const;

const components_dnd_indexRaw = `/**
 * Custom Pointer DnD library — public surface.
 *
 * A lightweight, pointer-event–based drag-and-drop primitive. More advanced
 * than the browser's native HTML5 drag API in several ways:
 *
 *   - **No flicker.** A single React state update per drop-slot change.
 *   - **Custom overlay.** A real React node follows the cursor.
 *   - **Activation distance.** Plain clicks still fire (>5px to start drag).
 *   - **Touch + mouse + pen** via Pointer Events.
 *   - **Axis-aware autoscroll** (vertical, horizontal, or both).
 *   - **Axis-aware index resolution** for vertical and horizontal lists.
 *   - **Escape to cancel.**
 *   - **Type-safe payloads** via generics.
 *
 * Used by: kanban board, table-builder row reorder + column reorder,
 * page-builder canvas, and anywhere else in the codebase that needs DnD.
 * Replaces all \`@dnd-kit/*\` usage.
 */
export { DndProvider, useDndContext } from "./DndContext";
export { useDraggable } from "./useDraggable";
export { useDropZone } from "./useDropZone";
export { DropIndicator } from "./DropIndicator";
export type {
  DragData,
  DragSnapshot,
  DropResult,
  HoverState,
  UseDraggableOptions,
  UseDropZoneOptions,
  ZoneRegistration,
  DndContextValue,
} from "./types";
`;
const components_dnd_DndContextRaw = `/**
 * Custom Pointer DnD — Context Provider (shared library).
 *
 * Promoted from \`src/components/kanban/dnd\` so it can power any builder
 * (kanban, table rows, page-builder canvas, column reordering, …).
 *
 * Improvements over the kanban-only version:
 *   - **Axis-aware autoscroll.** A zone may declare \`axis: "x"|"y"|"both"\`.
 *     The provider scrolls the nearest scrollable ancestor on the matching
 *     axis when the pointer hugs an edge.
 *   - **Axis-aware index resolver.** When \`axis: "x"\` we compare X midpoints
 *     instead of Y, so horizontal lists (kanban columns, table column reorder)
 *     compute the correct insertion index.
 *   - Same single-render-per-slot-change flicker-killer as before.
 *   - Same Escape-to-cancel and pointer-event coverage.
 */
import {
  useRef,
  useMemo,
  useState,
  useEffect,
  useContext,
  useCallback,
  createContext,
  type ReactNode,
} from "react";
import { createPortal } from "react-dom";

import type {
  HoverState,
  DragSnapshot,
  DndContextValue,
  ZoneRegistration,
} from "./types";

const DndCtx = createContext<DndContextValue | null>(null);

const AUTOSCROLL_EDGE = 56;
const AUTOSCROLL_MAX_SPEED = 18;

function findScrollableAncestor(
  el: HTMLElement | null,
  axis: "x" | "y" | "both",
): HTMLElement | Window {
  let node: HTMLElement | null = el;
  while (node && node !== document.body) {
    const style = window.getComputedStyle(node);
    const overflowY = style.overflowY;
    const overflowX = style.overflowX;
    const scrollableY =
      (overflowY === "auto" ||
        overflowY === "scroll" ||
        overflowY === "overlay") &&
      node.scrollHeight > node.clientHeight;
    const scrollableX =
      (overflowX === "auto" ||
        overflowX === "scroll" ||
        overflowX === "overlay") &&
      node.scrollWidth > node.clientWidth;
    if (axis === "y" && scrollableY) return node;
    if (axis === "x" && scrollableX) return node;
    if (axis === "both" && (scrollableX || scrollableY)) return node;
    node = node.parentElement;
  }
  return window;
}

function getScrollRect(target: HTMLElement | Window): DOMRect {
  if (target === window) {
    return new DOMRect(0, 0, window.innerWidth, window.innerHeight);
  }
  return (target as HTMLElement).getBoundingClientRect();
}

function scrollBy(target: HTMLElement | Window, dx: number, dy: number) {
  if (target === window) window.scrollBy(dx, dy);
  else {
    (target as HTMLElement).scrollTop += dy;
    (target as HTMLElement).scrollLeft += dx;
  }
}

function getDragCenter(snap: DragSnapshot) {
  return {
    x: snap.clientX - snap.offsetX + snap.width / 2,
    y: snap.clientY - snap.offsetY + snap.height / 2,
  };
}

function isPointInsideRect(x: number, y: number, rect: DOMRect) {
  return x >= rect.left && x <= rect.right && y >= rect.top && y <= rect.bottom;
}

function isPointInsideSourceBounds(x: number, y: number, snap: DragSnapshot) {
  return (
    snap.sourceLeft != null &&
    snap.sourceRight != null &&
    snap.sourceTop != null &&
    snap.sourceBottom != null &&
    x >= snap.sourceLeft &&
    x <= snap.sourceRight &&
    y >= snap.sourceTop &&
    y <= snap.sourceBottom
  );
}

/**
 * Returns the index of a sibling item (excluding the dragged one) whose
 * bounding rect contains the given point, or null if the point is in a
 * gap / outside any sibling.
 */
function findSiblingIndexAt(
  zoneEl: HTMLElement,
  x: number,
  y: number,
): { visibleIndex: number; rect: DOMRect } | null {
  const items = zoneEl.querySelectorAll<HTMLElement>('[data-dnd-item="true"]');
  let visibleIndex = 0;
  for (let i = 0; i < items.length; i += 1) {
    const el = items[i];
    if (el.dataset.dragging === "true") continue;
    const rect = el.getBoundingClientRect();
    if (
      x >= rect.left &&
      x <= rect.right &&
      y >= rect.top &&
      y <= rect.bottom
    ) {
      return { visibleIndex, rect };
    }
    visibleIndex += 1;
  }
  return null;
}

/**
 * Compute the insertion index inside \`zoneEl\` based on pointer position.
 * \`axis === "x"\` → compare X midpoints. Otherwise → Y midpoints.
 * Excludes the currently-dragging item via \`data-dragging="true"\`.
 * For \`axis === "x"\` in RTL containers, the comparison is inverted so the
 * computed index matches the visual order (rightmost item = index 0 in RTL).
 */
function resolveDropIndex(
  zoneEl: HTMLElement,
  clientX: number,
  clientY: number,
  axis: "x" | "y" | "grid",
): number {
  const items = zoneEl.querySelectorAll<HTMLElement>('[data-dnd-item="true"]');
  const isRtl =
    (axis === "x" || axis === "grid") &&
    window.getComputedStyle(zoneEl).direction === "rtl";
  let count = 0;

  if (axis === "grid") {
    // Group items into visual rows by Y midpoint, then resolve by X within row.
    const visible: { el: HTMLElement; rect: DOMRect }[] = [];
    for (let i = 0; i < items.length; i += 1) {
      const el = items[i];
      if (el.dataset.dragging === "true") continue;
      visible.push({ el, rect: el.getBoundingClientRect() });
    }
    if (visible.length === 0) return 0;

    const style = window.getComputedStyle(zoneEl);
    const columns = style.display.includes("grid")
      ? style.gridTemplateColumns.split(" ").filter(Boolean).length
      : 0;
    if (columns > 1) {
      const zoneRect = zoneEl.getBoundingClientRect();
      const columnGap = Number.parseFloat(style.columnGap) || 0;
      const rowGap = Number.parseFloat(style.rowGap) || 0;
      const cellWidth = (zoneRect.width - columnGap * (columns - 1)) / columns;
      const rowHeight = Math.max(...visible.map((item) => item.rect.height));
      const xInZone = Math.max(
        0,
        Math.min(clientX - zoneRect.left, zoneRect.width - 1),
      );
      const yInZone = Math.max(0, clientY - zoneRect.top);
      const trackWidth = cellWidth + columnGap;
      const rowStep = rowHeight + rowGap;
      const visualCol = Math.max(
        0,
        Math.min(columns - 1, Math.floor(xInZone / trackWidth)),
      );
      const col = isRtl ? columns - 1 - visualCol : visualCol;
      const row = Math.max(0, Math.floor(yInZone / rowStep));
      const rawIndex = row * columns + col;
      if (rawIndex >= visible.length) return visible.length;
      const cellStart = visualCol * trackWidth;
      const localX = xInZone - cellStart;
      const afterCellMidpoint = isRtl
        ? localX < cellWidth / 2
        : localX > cellWidth / 2;
      return Math.max(
        0,
        Math.min(visible.length, rawIndex + (afterCellMidpoint ? 1 : 0)),
      );
    }

    // Find the row the pointer is in (or before).
    for (let i = 0; i < visible.length; i += 1) {
      const { rect } = visible[i];
      const rowTop = rect.top;
      const rowBottom = rect.bottom;
      // Pointer above this item's row → insert here
      if (clientY < rowTop) return i;
      if (clientY <= rowBottom) {
        // Same row — pick by X midpoint
        const midX = rect.left + rect.width / 2;
        const before = isRtl ? clientX > midX : clientX < midX;
        if (before) return i;
      }
    }
    return visible.length;
  }

  for (let i = 0; i < items.length; i += 1) {
    const el = items[i];
    if (el.dataset.dragging === "true") continue;
    const rect = el.getBoundingClientRect();
    if (axis === "x") {
      const mid = rect.left + rect.width / 2;
      if (isRtl) {
        if (clientX > mid) return count;
      } else {
        if (clientX < mid) return count;
      }
    } else {
      if (clientY < rect.top + rect.height / 2) return count;
    }
    count += 1;
  }
  return count;
}

interface ProviderProps {
  children: ReactNode;
  onDragStart?: (snap: DragSnapshot) => void;
  onDragEnd?: (snap: DragSnapshot, dropped: boolean) => void;
  /**
   * Disable the smooth "make room" sibling translation animations.
   * Defaults to false. The provider also auto-disables animations when the
   * OS reports \`prefers-reduced-motion: reduce\`, regardless of this prop.
   */
  reduceMotion?: boolean;
}

export function DndProvider({
  children,
  onDragStart,
  onDragEnd,
  reduceMotion = false,
}: ProviderProps) {
  const zonesRef = useRef<Map<string, ZoneRegistration>>(new Map());
  const [active, setActive] = useState<DragSnapshot | null>(null);
  const [hover, setHover] = useState<HoverState | null>(null);
  const [overlay, setOverlay] = useState<{
    x: number;
    y: number;
    node: ReactNode;
  } | null>(null);
  const [systemReducedMotion, setSystemReducedMotion] = useState(false);

  useEffect(() => {
    if (typeof window === "undefined" || !window.matchMedia) return;
    const mq = window.matchMedia("(prefers-reduced-motion: reduce)");
    const update = () => setSystemReducedMotion(mq.matches);
    update();
    mq.addEventListener?.("change", update);
    return () => mq.removeEventListener?.("change", update);
  }, []);

  const animationsEnabled = !reduceMotion && !systemReducedMotion;

  const activeRef = useRef<DragSnapshot | null>(null);
  const hoverRef = useRef<HoverState | null>(null);
  const dropZoneCacheRef = useRef<{
    zone: ZoneRegistration;
    rect: DOMRect;
  } | null>(null);

  useEffect(() => {
    activeRef.current = active;
  }, [active]);
  useEffect(() => {
    hoverRef.current = hover;
  }, [hover]);

  const registerZone = useCallback((registration: ZoneRegistration) => {
    zonesRef.current.set(registration.id, registration);
    return () => {
      zonesRef.current.delete(registration.id);
    };
  }, []);

  const findZoneAt = useCallback(
    (clientX: number, clientY: number, snap: DragSnapshot) => {
      let result: { zone: ZoneRegistration; rect: DOMRect } | null = null;
      for (const zone of zonesRef.current.values()) {
        if (zone.accepts && !zone.accepts(snap)) continue;
        const rect = zone.element.getBoundingClientRect();
        if (
          clientX >= rect.left &&
          clientX <= rect.right &&
          clientY >= rect.top &&
          clientY <= rect.bottom
        ) {
          if (
            !result ||
            rect.width * rect.height < result.rect.width * result.rect.height
          ) {
            result = { zone, rect };
          }
        }
      }
      return result;
    },
    [],
  );

  // Auto-scroll while dragging near edges of the nearest scrollable ancestor of
  // the active drop-zone. Axis-aware so horizontal lists scroll horizontally.
  useEffect(() => {
    if (!active) return;
    let rafId = 0;
    let lastX = active.clientX;
    let lastY = active.clientY;

    const tick = () => {
      const cache = dropZoneCacheRef.current;
      const axis = (cache?.zone.axis ?? "y") as "x" | "y" | "both";
      const targetEl = cache
        ? findScrollableAncestor(cache.zone.element, axis)
        : window;
      const rect = getScrollRect(targetEl);

      let dx = 0;
      let dy = 0;
      if (axis === "y" || axis === "both") {
        const distFromTop = lastY - rect.top;
        const distFromBottom = rect.bottom - lastY;
        if (distFromTop < AUTOSCROLL_EDGE && distFromTop > 0) {
          dy =
            -((AUTOSCROLL_EDGE - distFromTop) / AUTOSCROLL_EDGE) *
            AUTOSCROLL_MAX_SPEED;
        } else if (distFromBottom < AUTOSCROLL_EDGE && distFromBottom > 0) {
          dy =
            ((AUTOSCROLL_EDGE - distFromBottom) / AUTOSCROLL_EDGE) *
            AUTOSCROLL_MAX_SPEED;
        }
      }
      if (axis === "x" || axis === "both") {
        const distFromLeft = lastX - rect.left;
        const distFromRight = rect.right - lastX;
        if (distFromLeft < AUTOSCROLL_EDGE && distFromLeft > 0) {
          dx =
            -((AUTOSCROLL_EDGE - distFromLeft) / AUTOSCROLL_EDGE) *
            AUTOSCROLL_MAX_SPEED;
        } else if (distFromRight < AUTOSCROLL_EDGE && distFromRight > 0) {
          dx =
            ((AUTOSCROLL_EDGE - distFromRight) / AUTOSCROLL_EDGE) *
            AUTOSCROLL_MAX_SPEED;
        }
      }
      if (dx !== 0 || dy !== 0) scrollBy(targetEl, dx, dy);
      rafId = requestAnimationFrame(tick);
    };

    const trackPos = (event: PointerEvent) => {
      lastX = event.clientX;
      lastY = event.clientY;
    };
    window.addEventListener("pointermove", trackPos, { passive: true });
    rafId = requestAnimationFrame(tick);

    return () => {
      window.removeEventListener("pointermove", trackPos);
      cancelAnimationFrame(rafId);
    };
  }, [active]);

  const beginDrag = useCallback<DndContextValue["beginDrag"]>(
    (payload, pointerEvent) => {
      const snap: DragSnapshot = {
        id: payload.id,
        data: payload.data,
        clientX: pointerEvent.clientX,
        clientY: pointerEvent.clientY,
        width: payload.width,
        height: payload.height,
        offsetX: payload.offsetX,
        offsetY: payload.offsetY,
        sourceLeft: payload.sourceLeft,
        sourceTop: payload.sourceTop,
        sourceRight: payload.sourceRight,
        sourceBottom: payload.sourceBottom,
      };
      setActive(snap);
      setOverlay({
        x: pointerEvent.clientX,
        y: pointerEvent.clientY,
        node: payload.preview ? payload.preview() : null,
      });
      if (typeof document !== "undefined") {
        document.body.style.cursor = "grabbing";
        document.body.style.userSelect = "none";
      }
      onDragStart?.(snap);

      let dropped = false;

      const handleMove = (event: PointerEvent) => {
        const next: DragSnapshot = {
          ...snap,
          clientX: event.clientX,
          clientY: event.clientY,
        };
        activeRef.current = next;
        setOverlay((prev) =>
          prev ? { ...prev, x: event.clientX, y: event.clientY } : prev,
        );

        const found = findZoneAt(event.clientX, event.clientY, next);
        dropZoneCacheRef.current = found;

        if (!found) {
          if (hoverRef.current !== null) {
            hoverRef.current = null;
            setHover(null);
          }
          return;
        }

        const zoneAxis = found.zone.axis;
        const axis = (
          zoneAxis === "x" ? "x" : zoneAxis === "grid" ? "grid" : "y"
        ) as "x" | "y" | "grid";
        const sourceIndex = found.zone.getItemIndex?.(next) ?? undefined;
        const center = getDragCenter(next);
        const prevHover = hoverRef.current;
        const sameZoneHover =
          prevHover && prevHover.zoneId === found.zone.id ? prevHover : null;

        let index: number;
        if (sourceIndex != null && sourceIndex >= 0) {
          // Sibling-based hit test: only update index when the cursor center is
          // actually inside another sibling. When in a gap, KEEP the previous
          // hover index to eliminate flicker as items reflow around the slot.
          const sibling = findSiblingIndexAt(
            found.zone.element,
            center.x,
            center.y,
          );
          if (sibling) {
            const horizontal = axis === "x" || axis === "grid";
            const mid = horizontal
              ? sibling.rect.left + sibling.rect.width / 2
              : sibling.rect.top + sibling.rect.height / 2;
            const coord = horizontal ? center.x : center.y;
            const after = coord > mid;
            index = sibling.visibleIndex + (after ? 1 : 0);
          } else if (sameZoneHover) {
            // Stay put in gaps — prevents flicker back to source position.
            index = sameZoneHover.index;
          } else {
            index = sourceIndex;
          }
        } else {
          index = resolveDropIndex(
            found.zone.element,
            center.x,
            center.y,
            axis,
          );
        }
        const nextHover: HoverState = {
          zoneId: found.zone.id,
          index,
          sourceIndex,
        };
        if (
          !prevHover ||
          prevHover.zoneId !== nextHover.zoneId ||
          prevHover.index !== nextHover.index ||
          prevHover.sourceIndex !== nextHover.sourceIndex
        ) {
          hoverRef.current = nextHover;
          setHover(nextHover);
        }
      };

      const cleanup = () => {
        window.removeEventListener("pointermove", handleMove);
        window.removeEventListener("pointerup", handleUp);
        window.removeEventListener("pointercancel", handleCancel);
        window.removeEventListener("keydown", handleKey);
        activeRef.current = null;
        hoverRef.current = null;
        dropZoneCacheRef.current = null;
        setActive(null);
        setHover(null);
        setOverlay(null);
        if (typeof document !== "undefined") {
          document.body.style.cursor = "";
          document.body.style.userSelect = "";
        }
        onDragEnd?.(snap, dropped);
      };

      const handleUp = (event: PointerEvent) => {
        const cache = dropZoneCacheRef.current;
        const finalSnap = {
          ...(activeRef.current ?? snap),
          clientX: event.clientX,
          clientY: event.clientY,
        };
        if (cache) {
          // Trust the last visible hover index — that is exactly what the user
          // saw as the drop target. Recomputing here can land back on the source
          // because items have already shifted to make room for the drop slot.
          const lastHover = hoverRef.current;
          let index: number;
          if (lastHover && lastHover.zoneId === cache.zone.id) {
            index = lastHover.index;
          } else {
            const cAxis = cache.zone.axis;
            const axis = (
              cAxis === "x" ? "x" : cAxis === "grid" ? "grid" : "y"
            ) as "x" | "y" | "grid";
            const center = getDragCenter(finalSnap);
            index = resolveDropIndex(
              cache.zone.element,
              center.x,
              center.y,
              axis,
            );
          }
          try {
            cache.zone.onDrop({
              item: finalSnap,
              zoneId: cache.zone.id,
              zoneData: cache.zone.data,
              index,
              clientX: event.clientX,
              clientY: event.clientY,
            });
            dropped = true;
          } catch (err) {
            console.error("[dnd] onDrop handler threw:", err);
          }
        }
        cleanup();
      };

      const handleCancel = () => cleanup();
      const handleKey = (event: KeyboardEvent) => {
        if (event.key === "Escape") cleanup();
      };

      window.addEventListener("pointermove", handleMove, { passive: true });
      window.addEventListener("pointerup", handleUp);
      window.addEventListener("pointercancel", handleCancel);
      window.addEventListener("keydown", handleKey);
    },
    [findZoneAt, onDragEnd, onDragStart],
  );

  const value = useMemo<DndContextValue>(
    () => ({
      active,
      hover,
      animationsEnabled,
      registerZone,
      beginDrag,
    }),
    [active, hover, animationsEnabled, registerZone, beginDrag],
  );

  return (
    <DndCtx.Provider value={value}>
      {children}
      {overlay &&
        typeof document !== "undefined" &&
        createPortal(
          (() => {
            const offX = active?.offsetX ?? 0;
            const offY = active?.offsetY ?? 0;
            const w = active?.width ?? 0;
            const h = active?.height ?? 0;
            const vw = typeof window !== "undefined" ? window.innerWidth : 0;
            const vh = typeof window !== "undefined" ? window.innerHeight : 0;
            const rawLeft = overlay.x - offX;
            const rawTop = overlay.y - offY;
            // Soft on-screen clamp: keep a small handle of the preview visible
            // rather than trying to fit the entire rectangle inside the
            // viewport. The old behavior (\`left ≤ vw - w - 4\`) broke wide
            // previews — e.g. a \`flex-1\` sortable row in the trash demo —
            // because as soon as \`w\` approached the viewport width, the
            // upper bound collapsed and the preview "stuck" mid-screen while
            // the cursor moved on. We now anchor on the cursor: it can drift
            // up to \`MIN_VISIBLE\` pixels past the preview's far edge, but no
            // further. That lets oversized previews slide partly off-screen
            // (so they keep tracking the pointer) without ever vanishing.
            const MIN_VISIBLE = 24;
            const minLeft = MIN_VISIBLE - Math.max(w, MIN_VISIBLE);
            const maxLeft = vw - MIN_VISIBLE;
            const minTop = MIN_VISIBLE - Math.max(h, MIN_VISIBLE);
            const maxTop = vh - MIN_VISIBLE;
            const left = Math.max(minLeft, Math.min(rawLeft, maxLeft));
            const top = Math.max(minTop, Math.min(rawTop, maxTop));
            return (
              <div
                style={{
                  position: "fixed",
                  left,
                  top,
                  pointerEvents: "none",
                  zIndex: 9999,
                  transform: "translateZ(0)",
                  opacity: 0.95,
                  filter: "drop-shadow(0 12px 24px rgba(0,0,0,0.18))",
                }}
                aria-hidden="true"
              >
                {overlay.node}
              </div>
            );
          })(),
          document.body,
        )}
    </DndCtx.Provider>
  );
}

export function useDndContext(): DndContextValue {
  const ctx = useContext(DndCtx);
  if (!ctx) {
    throw new Error("Custom DnD hooks must be used inside <DndProvider>.");
  }
  return ctx;
}
`;
const components_dnd_useDraggableRaw = `"use client";

/**
 * useDraggable — turn any element into a draggable handle.
 *
 * Usage:
 *   const { dragProps, isDragging } = useDraggable({
 *     id: card.id,
 *     data: { cardId: card.id, fromColumnId: col.id },
 *     preview: () => <KanbanCard card={card} />,
 *   });
 *   <div {...dragProps} data-dnd-item="true">…</div>
 *
 * Key behavior:
 *   - Activation distance: drag starts only after pointer moves > N px,
 *     so plain clicks still fire (good for "open card" handlers).
 *   - Pointer Events: works on touch + mouse + pen with no extra code.
 *   - We do NOT call setPointerCapture on the source — the pointer must
 *     stay free to hit-test drop zones underneath.
 *   - Sets \`data-dnd-item="true"\` so zones can find items, and
 *     \`data-dragging="true"\` on the source while active so the indexer
 *     skips it.
 */
import { useCallback, useMemo, useRef } from "react";
import { useDndContext } from "./DndContext";
import type { DragData, UseDraggableOptions } from "./types";

export function useDraggable<T extends DragData = DragData>(options: UseDraggableOptions<T>) {
  const { id, data, activationDistance = 5, disabled = false, preview } = options;
  const { beginDrag, active } = useDndContext();
  const startRef = useRef<{ x: number; y: number; pointerId: number } | null>(null);
  // The source element is captured from the PointerEvent target on PointerDown.
  const elementRef = useRef<HTMLElement | null>(null);

  const isDragging = active?.id === id;

  const onPointerDown = useCallback((event: React.PointerEvent<HTMLElement>) => {
    if (disabled) return;
    // Only primary pointer (left mouse / single touch / pen tip).
    if (event.pointerType === "mouse" && event.button !== 0) return;
    // Snapshot the source element on PointerDown so we can pass its size to
    // the provider when the activation distance is crossed.
    elementRef.current = event.currentTarget;
    startRef.current = {
      x: event.clientX,
      y: event.clientY,
      pointerId: event.pointerId,
    };

    const handleMove = (e: PointerEvent) => {
      const start = startRef.current;
      if (!start || start.pointerId !== e.pointerId) return;
      const dx = e.clientX - start.x;
      const dy = e.clientY - start.y;
      if (dx * dx + dy * dy < activationDistance * activationDistance) return;

      // Threshold crossed — promote to a real drag.
      window.removeEventListener("pointermove", handleMove);
      window.removeEventListener("pointerup", handleUp);
      window.removeEventListener("pointercancel", handleUp);
      startRef.current = null;
      const rect = elementRef.current?.getBoundingClientRect();
      beginDrag(
        {
          id,
          data,
          preview,
          width: rect?.width ?? 0,
          height: rect?.height ?? 0,
          offsetX: rect ? start.x - rect.left : 0,
          offsetY: rect ? start.y - rect.top : 0,
          sourceLeft: rect?.left,
          sourceTop: rect?.top,
          sourceRight: rect?.right,
          sourceBottom: rect?.bottom,
        },
        e,
      );
    };

    const handleUp = () => {
      window.removeEventListener("pointermove", handleMove);
      window.removeEventListener("pointerup", handleUp);
      window.removeEventListener("pointercancel", handleUp);
      startRef.current = null;
    };

    window.addEventListener("pointermove", handleMove, { passive: true });
    window.addEventListener("pointerup", handleUp);
    window.addEventListener("pointercancel", handleUp);
  }, [activationDistance, beginDrag, data, disabled, id, preview]);

  const dragProps = useMemo(() => ({
    onPointerDown,
    "data-dnd-item": "true" as const,
    "data-dragging": isDragging ? ("true" as const) : ("false" as const),
    // Prevent the browser from also starting a native HTML5 drag (image / link
    // drags) which would conflict with our pointer-based logic.
    draggable: false,
    style: {
      touchAction: "none" as const, // disable scroll gestures while interacting
      userSelect: "none" as const,
      WebkitUserSelect: "none" as const,
    },
  }), [isDragging, onPointerDown]);

  return { dragProps, isDragging };
}
`;
const components_dnd_useDropZoneRaw = `"use client";

/**
 * useDropZone — turn any element into a target for dropped draggables.
 *
 * Usage:
 *   const { zoneProps, isOver, hoverIndex } = useDropZone({
 *     id: column.id,
 *     data: { columnId: column.id },
 *     onDrop: ({ item, index }) => moveCard(item.data.cardId, column.id, index),
 *   });
 *   <div ref={zoneProps.ref}>…</div>
 *
 * Key behavior:
 *   - Registers the zone with the provider so the global pointermove handler
 *     can hit-test it (no per-zone listeners → no flicker storms).
 *   - Returns \`hoverIndex\` (computed midpoint index) when this zone is the
 *     active hover target, else null. Use it to render a single drop indicator
 *     at the right slot.
 *   - The zone callback fires AT MOST ONCE per drop and never on cancels.
 */
import { useCallback, useEffect, useMemo, useRef } from "react";
import { useDndContext } from "./DndContext";
import type { DragData, DropResult, UseDropZoneOptions } from "./types";

export function useDropZone<TZone extends DragData = DragData, TItem extends DragData = DragData>(
  options: UseDropZoneOptions<TZone, TItem>,
) {
  const { id, data, accepts, onDrop, disabled = false, axis = "y", getItemIndex } = options;
  const { active, hover, animationsEnabled, registerZone } = useDndContext();
  const elementRef = useRef<HTMLElement | null>(null);

  // Latest callbacks/data without forcing re-registration on every render.
  const handlersRef = useRef({ accepts, onDrop, data, getItemIndex });
  useEffect(() => {
    handlersRef.current = { accepts, onDrop, data, getItemIndex };
  }, [accepts, onDrop, data, getItemIndex]);

  const ref = useCallback((node: HTMLElement | null) => {
    elementRef.current = node;
  }, []);

  // Register / unregister whenever the actual DOM node or id changes — but
  // NOT on every onDrop change, since we read those from handlersRef.
  useEffect(() => {
    if (disabled) return;
    const node = elementRef.current;
    if (!node) return;

    const unregister = registerZone({
      id,
      element: node,
      get data() { return (handlersRef.current.data ?? {}) as DragData; },
      accepts: (drag) => {
        const fn = handlersRef.current.accepts;
        return fn ? fn(drag as never) : true;
      },
      onDrop: (result) => {
        handlersRef.current.onDrop(result as DropResult<TItem, TZone>);
      },
      getItemIndex: (drag) => handlersRef.current.getItemIndex?.(drag as never) ?? null,
      axis,
    });
    return unregister;
    // We intentionally re-register if \`disabled\` flips. The element ref is set
    // by \`ref\` callback before this effect runs (React commits refs first).
  }, [disabled, id, registerZone, axis]);

  const isOver = hover?.zoneId === id;
  const hoverIndex = isOver ? hover.index : null;

  const zoneProps = useMemo(() => ({
    ref,
    "data-dnd-zone": id,
    "data-dnd-over": isOver ? ("true" as const) : ("false" as const),
  }), [id, isOver, ref]);

  /**
   * Returns the inline style each rendered item in this zone should spread to
   * smoothly translate out of the way when a drag hovers over this zone, so
   * a real-sized gap opens at the insertion point — matching the dragged
   * card's exact dimensions, not a thin indicator bar.
   *
   *   - axis "y" → translateY by the dragged item's height (+ gap).
   *   - axis "x" → translateX (negated in RTL containers).
   *
   * Returns \`{}\` when the zone is not the hover target, when there is no
   * active drag, or when animations are disabled (reduce-motion).
   */
  const getItemSlotStyle = useCallback(
    (itemIndex: number): React.CSSProperties => {
      if (!isOver || hoverIndex == null || !active) return {};
      // The drag source collapses to height 0 (handled by the caller), so we
      // can treat every drop the same way: shift every sibling at-or-after
      // hoverIndex by exactly one slot. This eliminates the "two cards in the
      // same row" overlap that happened with sourceIndex-based shifting.
      if (itemIndex < hoverIndex) return {};
      const gap = 8;
      const transition = animationsEnabled
        ? "transform 200ms cubic-bezier(0.2, 0, 0, 1)"
        : "none";
      if (axis === "x") {
        const dx = active.width + gap;
        const isRtl = elementRef.current
          ? window.getComputedStyle(elementRef.current).direction === "rtl"
          : false;
        return {
          transform: \`translate3d(\${isRtl ? -dx : dx}px, 0, 0)\`,
          transition,
          willChange: "transform",
        };
      }
      return {
        transform: \`translate3d(0, \${active.height + gap}px, 0)\`,
        transition,
        willChange: "transform",
      };
    },
    [active, animationsEnabled, axis, hover, hoverIndex, id, isOver],
  );

  /** Size of the "ghost slot" placeholder rendered at the insertion point. */
  const slotSize = useMemo(
    () => ({ width: active?.width ?? 0, height: active?.height ?? 0 }),
    [active?.width, active?.height],
  );

  return {
    zoneProps,
    isOver,
    hoverIndex,
    isDragging: !!active,
    getItemSlotStyle,
    slotSize,
    animationsEnabled,
  };
}`;
const components_dnd_DropIndicatorRaw = `/**
 * Visual slot indicator rendered at the computed insertion index inside a zone.
 * Stable identity — same element, same key, no animation churn — eliminates the
 * "indicator flicker" that pure HTML5 DnD produces. Smoothly fades + scales in
 * so reorder feels animated even though we never re-mount items.
 */
import { cn } from "@/lib/utils";

interface Props {
  className?: string;
  /** Layout axis of the parent zone. Affects shape (horizontal bar vs vertical bar). */
  axis?: "x" | "y";
  /** When provided, the indicator renders as a real-sized "ghost slot" matching
   *  the dragged item's dimensions instead of a thin bar. */
  size?: { width: number; height: number };
  /** Disable the fade/zoom animation (used in reduce-motion mode). */
  animated?: boolean;
}

export function DropIndicator({ className, axis = "y", size, animated = true }: Props) {
  // Sized ghost slot — opens a real gap matching the dragged card. This is
  // what gives the board the "card slides into place" feel from the demo.
  if (size && size.width > 0 && size.height > 0) {
    return (
      <div
        aria-hidden="true"
        className={cn(
          "rounded-md border-2 border-dashed border-primary/50 bg-primary/10",
          animated && "animate-in fade-in zoom-in-95 duration-150",
          className,
        )}
        style={{ width: size.width, height: size.height }}
      />
    );
  }
  return (
    <div
      aria-hidden="true"
      className={cn(
        axis === "y" && "h-2 w-full rounded-sm border border-dashed border-primary/60 bg-primary/15",
        axis === "x" && "h-full min-h-8 w-2 rounded-sm border border-dashed border-primary/60 bg-primary/15 self-stretch",
        animated && "animate-in fade-in zoom-in-95 duration-150",
        className,
      )}
    />
  );
}`;
const components_dnd_typesRaw = `/**
 * Type contracts for the custom Pointer DnD library.
 *
 * The library is **pointer-event based** (not HTML5 native drag) so it:
 *   - never shows the OS ghost preview (no flicker)
 *   - works identically on touch & mouse via PointerEvents
 *   - lets us render a fully styled React overlay at the cursor
 *   - can autoscroll containers and cancel via Escape
 */

/** Anything the consumer wants to attach to a draggable. Stays type-safe via generics. */
export type DragData = Record<string, unknown>;

/** Snapshot of an active drag — passed to drop handlers. */
export interface DragSnapshot<T extends DragData = DragData> {
  /** Stable id of the dragged item. */
  id: string;
  /** Caller-supplied metadata (e.g. {cardId, fromColumnId, fromLane}). */
  data: T;
  /** Current pointer client coords. */
  clientX: number;
  clientY: number;
  /**
   * Bounding-box size of the dragged source element captured at drag start.
   * Used by drop zones to translate sibling items by the matching dimension
   * so a real "make room" gap opens, not just a thin indicator bar.
   */
  width: number;
  height: number;
  /** Pointer offset inside the source element at drag start. Keeps overlay under the cursor. */
  offsetX: number;
  offsetY: number;
  /** Source element bounds captured at drag start, used to avoid premature same-zone reflow. */
  sourceLeft?: number;
  sourceTop?: number;
  sourceRight?: number;
  sourceBottom?: number;
}

/** What a drop zone receives on a successful drop. */
export interface DropResult<TItem extends DragData = DragData, TZone extends DragData = DragData> {
  item: DragSnapshot<TItem>;
  zoneId: string;
  zoneData: TZone;
  /** Insertion index inside the zone (0..n) computed from pointer Y midpoints. */
  index: number;
  /** Pointer position at drop. */
  clientX: number;
  clientY: number;
}

/** Internal hover descriptor — shared via context so zones can render a single indicator. */
export interface HoverState {
  zoneId: string;
  index: number;
  /** Where the active item currently sits if it belongs to this same zone. */
  sourceIndex?: number;
}

/** Element registration for a drop zone (registered via useDropZone). */
export interface ZoneRegistration<TZone extends DragData = DragData> {
  id: string;
  data: TZone;
  element: HTMLElement;
  /** Should this zone accept the current drag? Defaults to true. */
  accepts?: (drag: DragSnapshot) => boolean;
  onDrop: (result: DropResult) => void;
  /** Return the active draggable's current index in this zone, or null if it is not from this zone. */
  getItemIndex?: (drag: DragSnapshot) => number | null;
  /**
   * Layout axis for index-resolution and edge autoscroll.
   *   "y"    — vertical list (default; index from Y midpoints)
   *   "x"    — horizontal list (index from X midpoints, X-axis autoscroll)
   *   "both" — autoscroll on either axis (kanban board scroll containers)
   *   "grid" — wrapping grid; index resolved row-then-column (Y, then X)
   */
  axis?: "x" | "y" | "both" | "grid";
}

export interface DndContextValue {
  /** Active drag snapshot, or null when idle. */
  active: DragSnapshot | null;
  /** Where the cursor is currently hovering (zone + computed insertion index). */
  hover: HoverState | null;
  /** Animations are honored by the lib. False when user opts out OR when the
   *  OS reports \`prefers-reduced-motion: reduce\`. */
  animationsEnabled: boolean;
  /** Register / unregister a drop zone. */
  registerZone: (registration: ZoneRegistration) => () => void;
  /** Begin a drag from a draggable. */
  beginDrag: (
    payload: {
      id: string;
      data: DragData;
      preview?: () => React.ReactNode;
      /** Size of the source element. Used to open a real-sized gap. */
      width: number;
      height: number;
      /** Pointer offset inside the source element. */
      offsetX: number;
      offsetY: number;
      sourceLeft?: number;
      sourceTop?: number;
      sourceRight?: number;
      sourceBottom?: number;
    },
    pointerEvent: PointerEvent,
  ) => void;
}

/** Options for useDraggable. */
export interface UseDraggableOptions<T extends DragData = DragData> {
  id: string;
  data: T;
  /** Pixels the pointer must move before a drag actually starts (default 5). */
  activationDistance?: number;
  /** Disable the draggable entirely. */
  disabled?: boolean;
  /** Optional custom React preview rendered inside the overlay. */
  preview?: () => React.ReactNode;
}

/** Options for useDropZone. */
export interface UseDropZoneOptions<TZone extends DragData = DragData, TItem extends DragData = DragData> {
  id: string;
  data?: TZone;
  accepts?: (drag: DragSnapshot<TItem>) => boolean;
  onDrop: (result: DropResult<TItem, TZone>) => void;
  /** Disable the zone entirely. */
  disabled?: boolean;
  /** Layout axis. Defaults to "y" (vertical list). */
  axis?: "x" | "y" | "both" | "grid";
  /** Return active draggable's current index in this zone; enables same-column make-room animation. */
  getItemIndex?: (drag: DragSnapshot<TItem>) => number | null;
}
`;
const components_dnd_dndRaw = `/**
 * Custom Pointer DnD — global styles.
 *
 * - Smooth transform transitions on items inside an active drop zone so that
 *   the visual gap created by <DropIndicator/> appearing/disappearing slides
 *   smoothly rather than snapping.
 * - The dragged item itself is excluded (it's already pinned to the cursor by
 *   the overlay portal).
 */
[data-dnd-zone="true"], [data-dnd-zone] {
  /* No-op selector — keeps Tailwind purger from dropping the data attribute. */
}

/* Smooth slide for siblings while a drag is in progress. */
[data-dnd-over="true"] [data-dnd-item="true"]:not([data-dragging="true"]) {
  transition: transform 180ms cubic-bezier(0.2, 0, 0, 1);
}

/* Visual treatment for the dragged source — the overlay shows the real card. */
[data-dnd-item="true"][data-dragging="true"] {
  transition: opacity 100ms ease-out;
}
`;

/** Always-shipped shared DnD primitive files. */
export const generatedSharedDndFiles: DndRegistryFile[] = [
  {
    name: "dnd/index.ts",
    path: "components/dnd/index.ts",
    code: components_dnd_indexRaw,
    language: "typescript",
    description: "Custom Pointer DnD — public surface (no @dnd-kit dependency).",
  },
  {
    name: "dnd/DndContext.tsx",
    path: "components/dnd/DndContext.tsx",
    code: components_dnd_DndContextRaw,
    language: "tsx",
    description: "DnD provider with autoscroll, prefers-reduced-motion, RTL index resolution.",
  },
  {
    name: "dnd/useDraggable.ts",
    path: "components/dnd/useDraggable.ts",
    code: components_dnd_useDraggableRaw,
    language: "typescript",
    description: "Draggable hook with activation distance + custom React preview.",
  },
  {
    name: "dnd/useDropZone.ts",
    path: "components/dnd/useDropZone.ts",
    code: components_dnd_useDropZoneRaw,
    language: "typescript",
    description: "DropZone hook with animated sibling 'make room' translation.",
  },
  {
    name: "dnd/DropIndicator.tsx",
    path: "components/dnd/DropIndicator.tsx",
    code: components_dnd_DropIndicatorRaw,
    language: "tsx",
    description: "Visual ghost-slot indicator at the computed insertion index.",
  },
  {
    name: "dnd/types.ts",
    path: "components/dnd/types.ts",
    code: components_dnd_typesRaw,
    language: "typescript",
    description: "Shared DnD type contracts.",
  },
  {
    name: "dnd/dnd.css",
    path: "components/dnd/dnd.css",
    code: components_dnd_dndRaw,
    language: "css",
    description: "DnD overlay/indicator animations + cursor styles. @import once at app entry.",
  },
];
