/**
 * AUTO-GENERATED by scripts/build-tree-registry.ts
 * DO NOT EDIT MANUALLY — run `npm run build:tree-registry` to regenerate.
 */

export interface TreeRegistryFile {
  name: string;
  path: string;
  code: string;
  language: "typescript" | "tsx" | "css";
  description: string;
}

export interface TreeOptionalGroup {
  feature: string;
  uiComponents: string[];
  npmDependencies: string[];
  files: TreeRegistryFile[];
}

export const treeRegistryGeneratedAt = "2026-07-15T02:59:38.788Z";

export const treeInstall = {
  "npmDependencies": [
    "react",
    "react-dom",
    "lucide-react",
    "clsx",
    "tailwind-merge"
  ],
  "npmDevDependencies": [],
  "uiComponents": [
    "badge"
  ]
} as const;

const components_tree_TreeCanvasRaw = `"use client";

/**
 * TreeCanvas — config-driven, zero-dependency tree renderer.
 *
 * Supports five layouts (horizontal · vertical · radial · mindmap · org),
 * pan + zoom, inline label editing, add/remove buttons and native pointer-based
 * drag-and-drop (reparent / make-sibling-before / make-sibling-after).
 *
 * Every mutation fires a separate handler so consumers can wire their own
 * backend without forking the engine:
 *
 *   <TreeCanvas
 *     config={{ layout: "horizontal", editable: true, draggable: true, ... }}
 *     tree={tree}
 *     onTreeChange={setTree}
 *     onNodeAdd={(e)    => api.create(e.parent.id, e.newNode)}
 *     onNodeUpdate={(e) => api.patch(e.node.id, { label: e.node.label })}
 *     onNodeRemove={(e) => api.delete(e.node.id)}
 *     onNodeMove={(e)   => api.move(e.node.id, e.next)}
 *   />
 */
import {
  useCallback, useMemo, useRef, useState, useEffect,
  type CSSProperties, type PointerEvent as ReactPointerEvent,
} from "react";
import { Plus, Pencil, Trash2, Check, X, Lock, GripVertical, ChevronUp, ChevronDown, ChevronLeft, ChevronRight, AlertTriangle } from "lucide-react";
import { cn } from "@/lib/utils";
import type {
  TreeCanvasConfig, TreeNode, TreeCanvasHandlers, TreeMoveMode,
  NodeRenderer,
} from "./types";
import { computeLayout, type LayoutEdge, type LayoutNode } from "./treeLayout";

interface Props extends TreeCanvasHandlers {
  config: TreeCanvasConfig;
  tree: TreeNode;
  onTreeChange?: (next: TreeNode) => void;
  className?: string;
  /** Set of ids that pass an external filter — non-matches are dimmed. */
  highlightIds?: Set<string>;
}

/* ---------- pure tree utilities (immutable) ---------- */

function findParent(root: TreeNode, id: string, parent: TreeNode | null = null): TreeNode | null {
  if (root.id === id) return parent;
  for (const c of root.children ?? []) {
    const r = findParent(c, id, root);
    if (r !== null) return r;
  }
  return null;
}
function findNode(root: TreeNode, id: string): TreeNode | null {
  if (root.id === id) return root;
  for (const c of root.children ?? []) {
    const r = findNode(c, id);
    if (r) return r;
  }
  return null;
}
function indexInParent(parent: TreeNode | null, id: string): number {
  if (!parent?.children) return -1;
  return parent.children.findIndex((c) => c.id === id);
}
function isDescendant(root: TreeNode, ancestorId: string, candidateId: string): boolean {
  const a = findNode(root, ancestorId);
  if (!a) return false;
  return !!findNode(a, candidateId);
}
function mapTree(root: TreeNode, fn: (n: TreeNode) => TreeNode): TreeNode {
  const next = fn(root);
  return { ...next, children: next.children?.map((c) => mapTree(c, fn)) };
}
function removeFromTree(root: TreeNode, id: string): TreeNode {
  return {
    ...root,
    children: (root.children ?? [])
      .filter((c) => c.id !== id)
      .map((c) => removeFromTree(c, id)),
  };
}
function collectSubtreeIds(n: TreeNode, out: Set<string> = new Set()): Set<string> {
  out.add(n.id);
  n.children?.forEach((c) => collectSubtreeIds(c, out));
  return out;
}
/** Move \`nodeId\` to become a child / sibling of \`targetId\` and return the new tree. */
function moveNode(
  root: TreeNode,
  nodeId: string,
  targetId: string,
  mode: TreeMoveMode,
): { tree: TreeNode; next: { parentId: string; index: number } } | null {
  if (nodeId === targetId) return null;
  if (nodeId === root.id) return null;
  if (isDescendant(root, nodeId, targetId)) return null; // can't drop into own subtree

  const node = findNode(root, nodeId);
  if (!node) return null;

  // Detach
  const stripped = removeFromTree(root, nodeId);

  if (mode === "child") {
    const next = mapTree(stripped, (n) =>
      n.id === targetId ? { ...n, children: [...(n.children ?? []), node] } : n,
    );
    const parent = findNode(next, targetId);
    return { tree: next, next: { parentId: targetId, index: (parent?.children?.length ?? 1) - 1 } };
  }

  // before / after — insert as sibling of target
  const targetParent = findParent(stripped, targetId);
  if (!targetParent) return null; // target was root
  const insertIdx = indexInParent(targetParent, targetId) + (mode === "after" ? 1 : 0);
  const next = mapTree(stripped, (n) => {
    if (n.id !== targetParent.id) return n;
    const kids = [...(n.children ?? [])];
    kids.splice(insertIdx, 0, node);
    return { ...n, children: kids };
  });
  return { tree: next, next: { parentId: targetParent.id, index: insertIdx } };
}
function uid(): string {
  return \`n_\${Math.random().toString(36).slice(2, 9)}\`;
}

/* ---------- main component ---------- */

export function TreeCanvas({
  config, tree, onTreeChange,
  onNodeAdd, onNodeUpdate, onNodeRemove, onNodeMove, onNodeClick,
  highlightIds, className,
}: Props) {
  const rawLayout = useMemo(
    () => computeLayout(tree, config.layout, {
      siblingGap: config.siblingGap,
      levelGap: config.levelGap,
    }),
    [tree, config.layout, config.siblingGap, config.levelGap],
  );

  // Resolve direction (explicit config wins, otherwise the document direction).
  const dir: "ltr" | "rtl" = config.dir
    ?? (typeof document !== "undefined" && document.dir === "rtl" ? "rtl" : "ltr");
  const horizontalAxisLayout = config.layout === "horizontal" || config.layout === "mindmap";

  /**
   * Apply RTL mirror (horizontal layouts only) + per-node free-position offsets.
   * Edges are mirrored/shifted by the same amount so connectors stay glued.
   */
  const layout = useMemo(() => {
    const offsetById = new Map<string, { dx: number; dy: number }>();
    const collect = (n: TreeNode) => {
      if (n.meta?.positionOffset) offsetById.set(n.id, n.meta.positionOffset);
      n.children?.forEach(collect);
    };
    collect(tree);
    const mirror = dir === "rtl" && horizontalAxisLayout;
    const w = rawLayout.width;
    const adjust = (x: number, width: number) => mirror ? w - x - width : x;
    const adjustPt = (x: number) => mirror ? w - x : x;
    return {
      ...rawLayout,
      nodes: rawLayout.nodes.map((n) => {
        const off = offsetById.get(n.id) ?? { dx: 0, dy: 0 };
        return { ...n, x: adjust(n.x, n.width) + off.dx, y: n.y + off.dy };
      }),
      edges: rawLayout.edges.map((e) => {
        const fromOff = offsetById.get(e.fromId) ?? { dx: 0, dy: 0 };
        const toOff = offsetById.get(e.toId) ?? { dx: 0, dy: 0 };
        const pts = e.points.map((p, i) => {
          const off = i === 0 ? fromOff : toOff;
          return { x: adjustPt(p.x) + off.dx, y: p.y + off.dy };
        });
        // RTL horizontal: swap parent/child endpoint ordering so curves still point outward.
        return { ...e, points: mirror ? [pts[pts.length - 1], pts[0]] : pts };
      }),
    };
  }, [rawLayout, tree, dir, horizontalAxisLayout]);

  const readOnly = config.readOnly === true;
  const allowAdd    = !readOnly && (config.allowAdd    ?? true);
  const allowEdit   = !readOnly && (config.allowEdit   ?? true);
  const allowDelete = !readOnly && (config.allowDelete ?? true);
  const allowDragG  = !readOnly && (config.allowDrag   ?? true);
  const editable    = !readOnly && config.editable !== false && (allowAdd || allowEdit || allowDelete);
  const draggable   = !readOnly && config.draggable === true && allowDragG;
  const structuredDndEnabled = !readOnly && allowDragG && (["child", "before", "after"] as const)
    .some((mode) => (config.dragModes?.[mode] ?? true) !== false);

  /** Per-node permission resolver — global flag wins, node \`meta.permissions\` can only further restrict. */
  const nodeCan = (n: TreeNode, kind: "add" | "edit" | "delete" | "drag"): boolean => {
    const globalOk = kind === "add" ? allowAdd : kind === "edit" ? allowEdit : kind === "delete" ? allowDelete : allowDragG;
    if (!globalOk) return false;
    if (n.meta?.locked) return false;
    const perm = n.meta?.permissions?.[kind];
    return perm !== false;
  };

  /* ---- pan + zoom (only when enabled) ---- */
  const [zoom, setZoom] = useState(1);
  const [offset, setOffset] = useState({ x: 24, y: 24 });
  const panRef = useRef<{ x: number; y: number; ox: number; oy: number } | null>(null);

  const onCanvasPointerDown = (e: ReactPointerEvent<HTMLDivElement>) => {
    if (!config.panZoom) return;
    if ((e.target as HTMLElement).closest("[data-tree-node]")) return;
    panRef.current = { x: e.clientX, y: e.clientY, ox: offset.x, oy: offset.y };
    (e.currentTarget as HTMLElement).setPointerCapture(e.pointerId);
  };
  const onCanvasPointerMove = (e: ReactPointerEvent<HTMLDivElement>) => {
    if (!panRef.current) return;
    setOffset({
      x: panRef.current.ox + (e.clientX - panRef.current.x),
      y: panRef.current.oy + (e.clientY - panRef.current.y),
    });
  };
  const onCanvasPointerUp = () => { panRef.current = null; };
  useEffect(() => {
    if (!config.panZoom) { setZoom(1); setOffset({ x: 24, y: 24 }); }
  }, [config.panZoom, config.layout]);

  /* ---- wheel / pinch zoom (touchpad pinch fires wheel + ctrlKey) ---- */
  const wheelHostRef = useRef<HTMLDivElement | null>(null);
  useEffect(() => {
    const el = wheelHostRef.current;
    if (!el || !config.panZoom) return;
    const onWheel = (e: WheelEvent) => {
      // Touchpad pinch (Mac/Win) emits wheel with ctrlKey; Ctrl/Cmd+wheel = explicit zoom.
      if (!(e.ctrlKey || e.metaKey)) return;
      e.preventDefault();
      const rect = el.getBoundingClientRect();
      const px = e.clientX - rect.left;
      const py = e.clientY - rect.top;
      setZoom((z) => {
        const factor = Math.exp(-e.deltaY * 0.0015);
        const next = Math.min(2, Math.max(0.4, z * factor));
        // Keep the point under the cursor stable.
        setOffset((o) => ({
          x: px - ((px - o.x) * next) / z,
          y: py - ((py - o.y) * next) / z,
        }));
        return next;
      });
    };
    el.addEventListener("wheel", onWheel, { passive: false });
    return () => el.removeEventListener("wheel", onWheel);
  }, [config.panZoom]);

  /* ---- mutations ---- */

  const commit = useCallback((next: TreeNode) => {
    onTreeChange?.(next);
    return next;
  }, [onTreeChange]);

  // Plain functions (no useCallback): the React Compiler auto-memoizes them.
  // Manual memoization can't be preserved here because \`nodeCan\` is a render-scope
  // helper, so we let the compiler handle it (repo convention).
  const handleAddChild = (parentId: string, blueprintId?: string) => {
    const parent = findNode(tree, parentId);
    if (!parent || !nodeCan(parent, "add")) return;
    const max = parent.meta?.maxChildren;
    if (max != null && (parent.children?.length ?? 0) >= max) return;
    const blueprint = blueprintId ? config.nodeBlueprints?.[blueprintId] : undefined;
    const newNode: TreeNode = blueprint
      ? {
          id: uid(),
          label: blueprint.label,
          meta: { ...(blueprint.meta ?? {}), blueprintId },
        }
      : { id: uid(), label: "New Step" };
    const next = mapTree(tree, (n) =>
      n.id === parentId ? { ...n, children: [...(n.children ?? []), newNode] } : n,
    );
    commit(next);
    const updatedParent = findNode(next, parentId)!;
    onNodeAdd?.({ parent: updatedParent, newNode, tree: next });
  };


  /** Reorder a node within its current parent by ±1 (chevron controls). */
  const handleReorder = useCallback((id: string, dir: -1 | 1) => {
    const parent = findParent(tree, id);
    if (!parent?.children) return;
    const idx = parent.children.findIndex((c) => c.id === id);
    const targetIdx = idx + dir;
    if (idx < 0 || targetIdx < 0 || targetIdx >= parent.children.length) return;
    const next = mapTree(tree, (n) => {
      if (n.id !== parent.id) return n;
      const kids = [...(n.children ?? [])];
      [kids[idx], kids[targetIdx]] = [kids[targetIdx], kids[idx]];
      return { ...n, children: kids };
    });
    commit(next);
    const node = findNode(next, id);
    if (node) {
      onNodeMove?.({
        node,
        prev: { parentId: parent.id, index: idx },
        next: { parentId: parent.id, index: targetIdx, mode: dir > 0 ? "after" : "before" },
        tree: next,
      });
    }
  }, [tree, commit, onNodeMove]);


  const handleUpdateLabel = (id: string, label: string) => {
    const prev = findNode(tree, id);
    if (!prev || !nodeCan(prev, "edit")) return;
    const next = mapTree(tree, (n) => (n.id === id ? { ...n, label } : n));
    commit(next);
    const updated = findNode(next, id)!;
    onNodeUpdate?.({ node: updated, prev, tree: next });
  };

  const handleRemove = (id: string) => {
    if (id === tree.id) return;
    const node = findNode(tree, id);
    const parent = findParent(tree, id);
    if (!node || !nodeCan(node, "delete")) return;
    const next = removeFromTree(tree, id);
    commit(next);
    onNodeRemove?.({ node, parent, tree: next });
  };

  /* ---- drag-and-drop (whole-node grab with 5px activation distance) ----
   *
   * Two distinct interactions share one pointer pipeline:
   *
   *   • "free"       — grab the node BODY. The whole subtree follows the
   *                    cursor as a rigid unit and, on drop, the delta is
   *                    persisted into \`meta.positionOffset\`. NO reparenting,
   *                    NO drop-child/before/after indicators.
   *
   *   • "structured" — grab the six-dot HANDLE. The node stays visually in
   *                    place; only drop-child/before/after logic runs, and
   *                    on drop the node is reparented / reordered. Any
   *                    accumulated \`positionOffset\` is reset so the node
   *                    lands cleanly at its new layout slot.
   */
  type DragMode = "free" | "structured";

  const horizontalAxis = horizontalAxisLayout;
  const [drag, setDrag] = useState<{
    id: string;
    mode: DragMode;
    pointer: { x: number; y: number };
    start: { x: number; y: number };
    subtreeIds: string[];
    over: { id: string; mode: TreeMoveMode } | null;
  } | null>(null);
  /** Pending drag — captured pointer-down state, promoted to active drag once
   *  the pointer moves >5px. Plain clicks (no movement) fire onNodeClick. */
  const pendingRef = useRef<{
    id: string; mode: DragMode; canDrag: boolean;
    startX: number; startY: number; pointerId: number; el: HTMLElement;
  } | null>(null);

  /** Suppresses left/top/transform transitions for exactly one paint frame
   *  right after a drop. This prevents the "slide-back" flicker where the
   *  browser interpolates from the pre-drag origin (\`ln.x\`) to the freshly
   *  persisted origin (\`ln.x + dx\`) while \`transform\` snaps to zero in the
   *  same commit. Cleared on the next rAF so subsequent layout changes
   *  (e.g. structured reparenting further away) still animate smoothly. */
  const [suppressTransitions, setSuppressTransitions] = useState(false);
  const snapshotThenClear = useCallback(() => {
    setSuppressTransitions(true);
    requestAnimationFrame(() => {
      requestAnimationFrame(() => setSuppressTransitions(false));
    });
  }, []);

  const beginPointerDown = (id: string, mode: DragMode) =>
    (e: ReactPointerEvent<HTMLElement>) => {
      if (id === tree.id) return; // root not draggable / clickable as a target
      if ((e.target as HTMLElement).closest("button, input")) return;
      if (typeof window !== "undefined") {
        const sel = window.getSelection();
        if (sel && sel.rangeCount > 0) sel.removeAllRanges();
      }
      const node = findNode(tree, id);
      // Per-node drag permission (\`meta.permissions.drag\` / \`meta.locked\`)
      // controls only FREE (body) drag, which physically repositions the
      // node. STRUCTURED (handle) drag never moves the node visually — it
      // only computes drop targets — so it stays enabled even when a node
      // has "drag" turned off, matching the whole-flow drag/drop split.
      const lockedNode = !!node?.meta?.locked;
      const canDrag = mode === "free"
        ? (!!node && nodeCan(node, "drag"))
        : (!!node && !lockedNode);
      // Global capability by mode.
      const globallyCapable = mode === "free" ? draggable : structuredDndEnabled;
      const dragEligible = canDrag && globallyCapable;
      // Record the pending pointer regardless so a plain click still fires
      // onNodeClick. \`canDrag\` short-circuits promotion in the move handler.
      pendingRef.current = {
        id, mode, canDrag: dragEligible,
        startX: e.clientX, startY: e.clientY, pointerId: e.pointerId,
        el: e.currentTarget as HTMLElement,
      };
      if (!dragEligible) return;
      e.stopPropagation();
      (e.currentTarget as HTMLElement).setPointerCapture(e.pointerId);
    };

  const handleNodePointerDown = (id: string) => beginPointerDown(id, "free");
  const handleHandlePointerDown = (id: string) => beginPointerDown(id, "structured");


  // Drop-axis inversion: when ON, drop indicators flip perpendicular to the
  // flow axis (horizontal flow → top/bottom, vertical flow → left/right).
  const siblingAxisInverted = config.siblingDndAxisInverted === true;
  const computeOverFromEvent = useCallback((e: PointerEvent | ReactPointerEvent): { id: string; mode: TreeMoveMode } | null => {
    const el = document.elementFromPoint(e.clientX, e.clientY);
    const nodeEl = el?.closest("[data-tree-node]") as HTMLElement | null;
    if (!nodeEl) return null;
    const targetId = nodeEl.getAttribute("data-tree-node");
    if (!targetId || targetId === drag?.id) return null;
    if (drag && isDescendant(tree, drag.id, targetId)) return null;
    const rect = nodeEl.getBoundingClientRect();
    // Drop axis: perpendicular to flow axis by default (see siblingAxisInverted above).
    const useHorizontalAxisForDrop = siblingAxisInverted ? !horizontalAxis : horizontalAxis;
    let ratio = useHorizontalAxisForDrop
      ? (e.clientX - rect.left) / rect.width
      : (e.clientY - rect.top) / rect.height;
    // RTL on horizontal: flip so the "left" half maps to "after" (visually earlier in RTL = later in source order).
    if (useHorizontalAxisForDrop && dir === "rtl" && horizontalAxisLayout) ratio = 1 - ratio;
    let mode: TreeMoveMode = ratio < 0.3 ? "before" : ratio > 0.7 ? "after" : "child";
    // Per-node + global dragModes gating — fall back to an allowed mode when
    // the computed one is disabled; return null if none of them are allowed.
    const targetNode = findNode(tree, targetId);
    const globalModes = config.dragModes ?? {};
    const nodeModes = targetNode?.meta?.dragModes ?? {};
    const allowed = {
      child:  (nodeModes.child  ?? globalModes.child  ?? true),
      before: (nodeModes.before ?? globalModes.before ?? true),
      after:  (nodeModes.after  ?? globalModes.after  ?? true),
    };
    if (!allowed[mode]) {
      // Try a graceful fallback: keep insertion side if possible, else flip.
      const order: TreeMoveMode[] = mode === "child"
        ? (ratio < 0.5 ? ["before", "after"] : ["after", "before"])
        : mode === "before" ? ["child", "after"] : ["child", "before"];
      const fallback = order.find((m) => allowed[m]);
      if (!fallback) return null;
      mode = fallback;
    }
    return { id: targetId, mode };
  }, [drag, tree, horizontalAxis, siblingAxisInverted, dir, horizontalAxisLayout, config.dragModes]);


  /** Persist a free-position offset onto a node (Alt+drag drop). */
  const handleFreeMove = useCallback((id: string, delta: { dx: number; dy: number }) => {
    if (delta.dx === 0 && delta.dy === 0) return;
    const prev = findNode(tree, id);
    if (!prev) return;
    const existing = prev.meta?.positionOffset ?? { dx: 0, dy: 0 };
    const newOff = { dx: existing.dx + delta.dx, dy: existing.dy + delta.dy };
    const next = mapTree(tree, (n) =>
      n.id === id ? { ...n, meta: { ...n.meta, positionOffset: newOff } } : n,
    );
    commit(next);
    const updated = findNode(next, id)!;
    onNodeUpdate?.({ node: updated, prev, tree: next });
  }, [tree, commit, onNodeUpdate]);

  /** Promote a pending pointer-down to an active drag once the pointer has
   *  travelled >5px. If the pointer comes up first, treat it as a click. */
  useEffect(() => {
    const ACTIVATION = 5;
    const onMove = (e: PointerEvent) => {
      if (drag) {
        // Structured mode → hit-test for drop target. Free mode → just track pointer.
        const over = drag.mode === "structured" ? computeOverFromEvent(e) : null;
        setDrag((d) => d ? { ...d, pointer: { x: e.clientX, y: e.clientY }, over } : d);
        return;
      }
      const p = pendingRef.current;
      if (!p) return;
      const dx = e.clientX - p.startX;
      const dy = e.clientY - p.startY;
      if (dx * dx + dy * dy > ACTIVATION * ACTIVATION) {
        if (!p.canDrag) return; // per-node drag disabled — never promote
        const capable = p.mode === "free" ? draggable : structuredDndEnabled;
        if (!capable) return;
        const node = findNode(tree, p.id);
        const subtreeIds = node ? Array.from(collectSubtreeIds(node)) : [p.id];
        setDrag({
          id: p.id,
          mode: p.mode,
          pointer: { x: e.clientX, y: e.clientY },
          start: { x: p.startX, y: p.startY },
          subtreeIds,
          over: null,
        });
      }
    };
    const onUp = (e: PointerEvent) => {
      const p = pendingRef.current;
      if (drag) {
        if (drag.mode === "free") {
          // Free reposition — persist the pointer delta as a positionOffset.
          const dx = (e.clientX - drag.start.x) / zoom;
          const dy = (e.clientY - drag.start.y) / zoom;
          const ids = new Set(drag.subtreeIds);
          if (dx === 0 && dy === 0) {
            setDrag(null);
            pendingRef.current = null;
            return;
          }
          const prev = findNode(tree, drag.id);
          if (!prev) { setDrag(null); pendingRef.current = null; return; }
          const next = mapTree(tree, (n) => {
            if (!ids.has(n.id)) return n;
            const existing = n.meta?.positionOffset ?? { dx: 0, dy: 0 };
            return { ...n, meta: { ...n.meta, positionOffset: { dx: existing.dx + dx, dy: existing.dy + dy } } };
          });
          // Suppress transitions BEFORE the commit so the new left/top lands
          // atomically with the removal of the transform — no slide-back.
          snapshotThenClear();
          commit(next);
          setDrag(null);
          pendingRef.current = null;
          const updated = findNode(next, drag.id)!;
          onNodeUpdate?.({ node: updated, prev, tree: next });
          return;
        }
        // Structured reparent / reorder.
        const target = computeOverFromEvent(e);
        if (!target) {
          setDrag(null);
          pendingRef.current = null;
          return;
        }
        const prevParent = findParent(tree, drag.id);
        const prevIndex = indexInParent(prevParent, drag.id);
        const node = findNode(tree, drag.id);
        const moveResult = moveNode(tree, drag.id, target.id, target.mode);
        if (!moveResult || !node) {
          setDrag(null);
          pendingRef.current = null;
          return;
        }
        // Reset positionOffset on the moved node so it snaps to its new
        // layout slot cleanly — no double-offset flicker.
        const cleared = mapTree(moveResult.tree, (n) =>
          n.id === drag.id && n.meta?.positionOffset
            ? { ...n, meta: { ...n.meta, positionOffset: undefined } }
            : n,
        );
        // Structured drops: also suppress the one-frame transition kick so
        // the node lands cleanly. Subsequent layout shifts of siblings still
        // animate because the flag clears on the next rAF.
        snapshotThenClear();
        commit(cleared);
        setDrag(null);
        pendingRef.current = null;
        onNodeMove?.({
          node,
          prev: { parentId: prevParent?.id ?? null, index: prevIndex },
          next: { ...moveResult.next, mode: target.mode },
          tree: cleared,
        });
        return;
      }
      if (p) {
        const dx = e.clientX - p.startX;
        const dy = e.clientY - p.startY;
        if (dx * dx + dy * dy <= ACTIVATION * ACTIVATION) {
          const node = findNode(tree, p.id);
          if (node) onNodeClick?.(node);
        }
        pendingRef.current = null;
      }
    };
    const onCancel = () => { setDrag(null); pendingRef.current = null; };
    window.addEventListener("pointermove", onMove);
    window.addEventListener("pointerup", onUp);
    window.addEventListener("pointercancel", onCancel);
    return () => {
      window.removeEventListener("pointermove", onMove);
      window.removeEventListener("pointerup", onUp);
      window.removeEventListener("pointercancel", onCancel);
    };
  }, [drag, draggable, structuredDndEnabled, computeOverFromEvent, tree, commit, onNodeMove, onNodeClick, onNodeUpdate, zoom, snapshotThenClear]);


  /* ---- auto-scroll the window while dragging near a viewport edge ---- */
  useEffect(() => {
    if (!drag) return;
    const EDGE = 80;       // px from edge that triggers scroll
    const MAX_SPEED = 24;  // px per frame
    let raf = 0;
    const tick = () => {
      const { x, y } = drag.pointer;
      const vw = window.innerWidth;
      const vh = window.innerHeight;
      let dx = 0, dy = 0;
      if (y < EDGE)             dy = -MAX_SPEED * (1 - y / EDGE);
      else if (y > vh - EDGE)   dy =  MAX_SPEED * (1 - (vh - y) / EDGE);
      if (x < EDGE)             dx = -MAX_SPEED * (1 - x / EDGE);
      else if (x > vw - EDGE)   dx =  MAX_SPEED * (1 - (vw - x) / EDGE);
      if (dx !== 0 || dy !== 0) {
        // Scroll the nearest scrollable ancestor (canvas container, panel,
        // or window) so users can drag onto offscreen nodes.
        const target = document.elementFromPoint(x, y) as HTMLElement | null;
        let scrolled = false;
        let el: HTMLElement | null = target;
        while (el && el !== document.body) {
          const cs = getComputedStyle(el);
          const oy = cs.overflowY, ox = cs.overflowX;
          const scrollableY = (oy === "auto" || oy === "scroll") && el.scrollHeight > el.clientHeight;
          const scrollableX = (ox === "auto" || ox === "scroll") && el.scrollWidth > el.clientWidth;
          if (scrollableY || scrollableX) {
            if (scrollableY) el.scrollTop += dy;
            if (scrollableX) el.scrollLeft += dx;
            scrolled = true;
            break;
          }
          el = el.parentElement;
        }
        if (!scrolled) window.scrollBy(dx, dy);
      }
      raf = requestAnimationFrame(tick);
    };
    raf = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(raf);
  }, [drag]);

  /* ---- render ---- */

  const padding = 48;
  const canvasW = Math.max(layout.width + padding * 2, 320);
  const canvasH = Math.max(layout.height + padding * 2, config.minHeight ?? 320);

  // Live visual delta — ONLY applied in "free" drags. Structured (handle)
  // drags leave the node visually pinned and instead show drop indicators
  // on the hovered target.
  const liveFreeDelta = drag && drag.mode === "free"
    ? { dx: (drag.pointer.x - drag.start.x) / zoom, dy: (drag.pointer.y - drag.start.y) / zoom }
    : null;
  const liveSubtreeIds = liveFreeDelta && drag ? new Set(drag.subtreeIds) : null;

  const resolveEdgePoints = useCallback((edge: LayoutEdge) => {
    let a = edge.points[0];
    let b = edge.points[edge.points.length - 1];
    if (!liveFreeDelta || !liveSubtreeIds) return { a, b };

    const fromInDraggedSubtree = liveSubtreeIds.has(edge.fromId);
    const toInDraggedSubtree = liveSubtreeIds.has(edge.toId);
    if (fromInDraggedSubtree) a = { x: a.x + liveFreeDelta.dx, y: a.y + liveFreeDelta.dy };
    if (toInDraggedSubtree) b = { x: b.x + liveFreeDelta.dx, y: b.y + liveFreeDelta.dy };
    return { a, b };
  }, [liveFreeDelta, liveSubtreeIds]);

  const bgClass = config.background === "dots"
    ? "bg-[radial-gradient(circle,_hsl(var(--border))_1px,_transparent_1px)] [background-size:18px_18px]"
    : config.background === "grid"
    ? "bg-[linear-gradient(to_right,hsl(var(--border))_1px,transparent_1px),linear-gradient(to_bottom,hsl(var(--border))_1px,transparent_1px)] [background-size:24px_24px]"
    : config.background === "cross"
    ? "bg-[linear-gradient(to_right,hsl(var(--border))_1px,transparent_1px),linear-gradient(to_bottom,hsl(var(--border))_1px,transparent_1px)] [background-size:40px_40px] [background-position:center]"
    : config.background === "diagonal"
    ? "bg-[repeating-linear-gradient(45deg,hsl(var(--border))_0_1px,transparent_1px_14px)]"
    : config.background === "blueprint"
    ? "bg-[linear-gradient(to_right,hsl(var(--primary)/0.18)_1px,transparent_1px),linear-gradient(to_bottom,hsl(var(--primary)/0.18)_1px,transparent_1px)] [background-size:24px_24px] bg-[hsl(var(--primary)/0.04)]"
    : "";

  return (
    <div ref={wheelHostRef} dir={dir} className={cn("relative w-full overflow-hidden rounded-lg border border-border bg-card",
      bgClass, className)}
      style={{ height: canvasH }}
    >
      {/* zoom controls */}
      {config.panZoom && (
        <div className="absolute top-3 right-3 z-20 flex items-center gap-1 rounded-md border border-border bg-background/90 backdrop-blur px-1 py-0.5 shadow-sm">
          <button onClick={() => setZoom((z) => Math.max(0.4, z - 0.1))}
            className="h-7 w-7 rounded hover:bg-muted text-sm">−</button>
          <span className="text-xs font-mono w-10 text-center">{Math.round(zoom * 100)}%</span>
          <button onClick={() => setZoom((z) => Math.min(2, z + 0.1))}
            className="h-7 w-7 rounded hover:bg-muted text-sm">+</button>
          <button onClick={() => { setZoom(1); setOffset({ x: 24, y: 24 }); }}
            className="h-7 px-2 rounded hover:bg-muted text-xs">Reset</button>
        </div>
      )}

      {/* read-only badge */}
      {readOnly && (
        <div className="absolute top-3 left-3 z-20 inline-flex items-center gap-1 rounded-md border border-border bg-background/90 backdrop-blur px-2 py-0.5 text-[10px] font-semibold uppercase tracking-widest text-muted-foreground">
          <Lock className="h-3 w-3" /> Read-only
        </div>
      )}

      <div
        className={cn("absolute inset-0", config.panZoom && "cursor-grab active:cursor-grabbing")}
        onPointerDown={onCanvasPointerDown}
        onPointerMove={onCanvasPointerMove}
        onPointerUp={onCanvasPointerUp}
      >
        <div
          style={{
            transform: \`translate(\${offset.x}px, \${offset.y}px) scale(\${zoom})\`,
            transformOrigin: "0 0",
            width: canvasW, height: canvasH,
            position: "relative",
          }}
        >
          {/* edges */}
          <svg
            width={canvasW} height={canvasH}
            className="absolute inset-0 pointer-events-none"
            style={{ overflow: "visible" }}
          >
            {layout.edges.map((e) => (
              (() => {
                const { a, b } = resolveEdgePoints(e);
                return (
                  <ConnectorPath
                    key={\`\${e.fromId}-\${e.toId}\`}
                    a={a}
                    b={b}
                    style={config.connector ?? "curved"}
                    axis={config.layout}
                  />
                );
              })()
            ))}
          </svg>

          {/* edge labels — rendered as absolutely positioned pills above edges */}
          {layout.edges.filter((e) => e.label).map((e) => {
            const { a, b } = resolveEdgePoints(e);
            const mx = (a.x + b.x) / 2;
            const my = (a.y + b.y) / 2;
            return (
              <div
                key={\`label-\${e.fromId}-\${e.toId}\`}
                className="absolute z-[1] pointer-events-none px-1.5 py-0.5 rounded border border-border bg-background text-[10px] font-medium text-foreground shadow-sm whitespace-nowrap"
                style={{ left: mx, top: my, transform: "translate(-50%, -50%)" }}
              >
                {e.label}
              </div>
            );
          })}

          {/* nodes */}
          {layout.nodes.map((ln) => {
            const parent = ln.parentId ? findNode(tree, ln.parentId) : null;
            const siblings = parent?.children ?? [];
            const idxInParent = siblings.findIndex((c) => c.id === ln.id);
            const canMovePrev = idxInParent > 0;
            const canMoveNext = idxInParent >= 0 && idxInParent < siblings.length - 1;
            const max = ln.node.meta?.maxChildren;
            const childCount = ln.node.children?.length ?? 0;
            const canAddChild = (max == null || childCount < max) && nodeCan(ln.node, "add");
            const overLimit = max != null && childCount > max;
            const canEditNode = nodeCan(ln.node, "edit");
            const canDeleteNode = nodeCan(ln.node, "delete");
            const canDragNode = nodeCan(ln.node, "drag");
            const canStartDragNode = canDragNode && (draggable || structuredDndEnabled);
            // Resolve blueprint picker options for this node (if any).
            const allowed = ln.node.meta?.allowedChildren;
            const blueprints = config.nodeBlueprints;
            const blueprintOptions =
              allowed && blueprints
                ? allowed
                    .map((id) => (blueprints[id] ? { id, ...blueprints[id] } : null))
                    .filter((x): x is { id: string; label: string; meta?: Partial<import("./types").TreeNodeMeta>; description?: string } => x !== null)
                : undefined;
            // Drop indicator axis: flip perpendicular to flow when invert is on,
            // independent of sibling-only mode.
            const chevronAxis: "horizontal" | "vertical" =
              siblingAxisInverted ? (horizontalAxis ? "vertical" : "horizontal") : (horizontalAxis ? "horizontal" : "vertical");
            // Resolution order: per-node override → flow default → built-in.
            const renderer: NodeRenderer | null =
              ln.node.meta?.render ?? config.renderNode ?? null;
            return (
              <NodeView
                key={ln.id}
                ln={ln}
                editable={editable && (canAddChild || canEditNode || canDeleteNode)}
                canEdit={canEditNode}
                canDelete={canDeleteNode}
                draggable={canStartDragNode}
                clickable={!!onNodeClick}
                shape={ln.node.meta?.shape ?? config.nodeShape ?? "rounded"}
                renderer={renderer}
                showLevelLabel={config.showLevelLabels !== false}
                isRoot={ln.id === tree.id}
                isDragging={drag?.id === ln.id}
                suppressTransition={suppressTransitions}
                freeMoveDelta={liveFreeDelta && liveSubtreeIds?.has(ln.id) ? liveFreeDelta : null}
                dimmed={highlightIds ? !highlightIds.has(ln.id) && ln.id !== tree.id : false}
                dropMode={drag?.over?.id === ln.id ? drag.over.mode : null}
                dropAxis={chevronAxis}
                showPositionControls={config.showPositionControls === true && !readOnly && !ln.node.meta?.locked}
                canMovePrev={canMovePrev}
                canMoveNext={canMoveNext}
                canAddChild={canAddChild}
                maxChildren={max ?? null}
                childCount={childCount}
                overLimit={overLimit}
                depth={ln.depth}
                blueprintOptions={blueprintOptions}
                onReorder={(d) => handleReorder(ln.id, d)}
                onPointerDown={handleNodePointerDown(ln.id)}
                onHandlePointerDown={handleHandlePointerDown(ln.id)}
                structuredDndEnabled={structuredDndEnabled}
                onAdd={(blueprintId) => handleAddChild(ln.id, blueprintId)}
                onUpdate={(label) => handleUpdateLabel(ln.id, label)}
                onRemove={() => handleRemove(ln.id)}

              />
            );
          })}


        </div>
      </div>

      {/* Drag ghost intentionally omitted — the dragged subtree itself
          (nodes + connector branches) now follows the pointer via
          liveFreeDelta, so a floating label pill would be redundant. */}
    </div>
  );
}

/* ---------- helpers ---------- */

function ConnectorPath({
  a, b, style, axis,
}: {
  a: { x: number; y: number };
  b: { x: number; y: number };
  style: "straight" | "stepped" | "curved" | "dashed";
  axis: TreeCanvasConfig["layout"];
}) {
  const stroke = "hsl(var(--border))";
  const dash = style === "dashed" ? "4 4" : undefined;

  let d = "";
  if (style === "straight" || style === "dashed") {
    d = \`M \${a.x} \${a.y} L \${b.x} \${b.y}\`;
  } else if (style === "stepped") {
    const mid = axis === "vertical" || axis === "org"
      ? (a.y + b.y) / 2
      : (a.x + b.x) / 2;
    d = axis === "vertical" || axis === "org"
      ? \`M \${a.x} \${a.y} L \${a.x} \${mid} L \${b.x} \${mid} L \${b.x} \${b.y}\`
      : \`M \${a.x} \${a.y} L \${mid} \${a.y} L \${mid} \${b.y} L \${b.x} \${b.y}\`;
  } else {
    const dx = b.x - a.x;
    const dy = b.y - a.y;
    const c1 = axis === "vertical" || axis === "org"
      ? { x: a.x, y: a.y + dy * 0.5 }
      : { x: a.x + dx * 0.5, y: a.y };
    const c2 = axis === "vertical" || axis === "org"
      ? { x: b.x, y: b.y - dy * 0.5 }
      : { x: b.x - dx * 0.5, y: b.y };
    d = \`M \${a.x} \${a.y} C \${c1.x} \${c1.y}, \${c2.x} \${c2.y}, \${b.x} \${b.y}\`;
  }
  return <path d={d} stroke={stroke} strokeWidth={1.5} fill="none" strokeDasharray={dash} />;
}

function NodeView({
  ln, editable, canEdit, canDelete, draggable, clickable, dimmed, shape, showLevelLabel, isRoot,
  renderer,
  isDragging, suppressTransition, freeMoveDelta, dropMode, dropAxis,
  showPositionControls, canMovePrev, canMoveNext, canAddChild, maxChildren, childCount, overLimit, depth,
  blueprintOptions,
  onReorder, onPointerDown, onHandlePointerDown, structuredDndEnabled, onAdd, onUpdate, onRemove,
}: {
  ln: LayoutNode;
  editable: boolean;
  canEdit: boolean;
  canDelete: boolean;
  draggable: boolean;
  clickable: boolean;
  dimmed: boolean;
  shape: "rect" | "rounded" | "pill" | "diamond" | "circle";
  renderer: NodeRenderer | null;
  showLevelLabel: boolean;
  isRoot: boolean;
  isDragging: boolean;
  suppressTransition: boolean;
  freeMoveDelta: { dx: number; dy: number } | null;
  dropMode: TreeMoveMode | null;
  dropAxis: "horizontal" | "vertical";
  showPositionControls: boolean;
  canMovePrev: boolean;
  canMoveNext: boolean;
  canAddChild: boolean;
  maxChildren: number | null;
  childCount: number;
  overLimit: boolean;
  depth: number;
  blueprintOptions?: { id: string; label: string; description?: string }[];
  onReorder: (dir: -1 | 1) => void;
  onPointerDown: (e: ReactPointerEvent<HTMLElement>) => void;
  onHandlePointerDown: (e: ReactPointerEvent<HTMLElement>) => void;
  structuredDndEnabled: boolean;
  onAdd: (blueprintId?: string) => void;
  onUpdate: (label: string) => void;
  onRemove: () => void;

}) {
  const [editing, setEditing] = useState(false);
  const [draft, setDraft] = useState(ln.node.label);
  useEffect(() => setDraft(ln.node.label), [ln.node.label]);

  const locked = ln.node.meta?.locked;
  const accent = ln.node.meta?.color ?? "hsl(var(--primary))";

  const shapeClass =
    shape === "rect" ? "rounded-none"
    : shape === "rounded" ? "rounded-md"
    : shape === "pill" ? "rounded-full"
    : shape === "circle" ? "rounded-full"
    : "rounded-md";

  const baseStyle: CSSProperties = {
    left: ln.x, top: ln.y,
    width: ln.width, height: ln.height,
    borderColor: isRoot ? accent : undefined,
    transform: freeMoveDelta ? \`translate3d(\${freeMoveDelta.dx}px, \${freeMoveDelta.dy}px, 0)\` : undefined,
    zIndex: freeMoveDelta ? 30 : undefined,
    // Smooth the layout snap that follows a structured reparent / reorder.
    // During an active drag we disable it so the pointer feels 1:1.
    transition: freeMoveDelta || isDragging || suppressTransition
      ? "none"
      : "left 180ms cubic-bezier(0.2,0,0,1), top 180ms cubic-bezier(0.2,0,0,1), box-shadow 150ms, opacity 150ms, transform 150ms",
    willChange: freeMoveDelta ? "transform" : undefined,
    userSelect: "none",
    WebkitUserSelect: "none",
    touchAction: "none",
  };

  const transform = shape === "diamond" ? "rotate(45deg)" : undefined;
  const innerTransform = shape === "diamond" ? "rotate(-45deg)" : undefined;

  const interactive = (draggable || clickable) && !isRoot && !locked && !editing;

  // Render-function output (per-node override → flow default → built-in body).
  const customBody = renderer
    ? renderer({ node: ln.node, childCount, depth, isRoot })
    : null;

  return (
    <div
      data-tree-node={ln.id}
      style={baseStyle}
      onPointerDown={interactive ? onPointerDown : undefined}
      className={cn(
        "absolute group flex items-center justify-center shadow-sm border bg-card",
        "select-none",
        shapeClass,
        isRoot && "border-2",
        isDragging && !freeMoveDelta && "opacity-40 scale-95",
        dimmed && "opacity-25",
        interactive && (draggable ? "cursor-grab active:cursor-grabbing" : "cursor-pointer"),
        dropMode === "child" && "ring-2 ring-primary ring-offset-2 ring-offset-background",
      )}
    >

      {/* drop indicators (before / after) */}
      {dropMode === "before" && (
        <span className={cn(
          "absolute bg-primary rounded-full",
          dropAxis === "horizontal" ? "left-[-6px] top-0 bottom-0 w-[3px]" : "top-[-6px] left-0 right-0 h-[3px]",
        )} />
      )}
      {dropMode === "after" && (
        <span className={cn(
          "absolute bg-primary rounded-full",
          dropAxis === "horizontal" ? "right-[-6px] top-0 bottom-0 w-[3px]" : "bottom-[-6px] left-0 right-0 h-[3px]",
        )} />
      )}

      {showLevelLabel && ln.node.meta?.badge && (
        <div className="absolute -top-5 left-0 right-0 text-center text-[9px] font-bold uppercase tracking-widest text-muted-foreground">
          {ln.node.meta.badge}
        </div>
      )}

      {/* Structured-DnD handle — dragging THIS icon activates reparent /
          reorder logic without moving the node's visual position. Body drags
          remain free-reposition-only. */}
      {structuredDndEnabled && !isRoot && !locked && (
        <span
          onPointerDown={(e) => { e.stopPropagation(); onHandlePointerDown(e); }}
          title="Drag from here to reparent or reorder"
          className="absolute -left-3 top-1/2 -translate-y-1/2 z-20 h-6 w-5 rounded border border-border bg-background grid place-items-center opacity-0 group-hover:opacity-100 cursor-grab active:cursor-grabbing shadow-sm"
          style={{ touchAction: "none" }}
        >
          <GripVertical className="h-3.5 w-3.5 text-muted-foreground" />
        </span>
      )}


      <div
        style={{ transform }}
        className={cn("flex h-full w-full items-center justify-center", shapeClass,
          shape === "diamond" && "border bg-card")}
      >
        <div style={{ transform: innerTransform }} className="flex flex-col items-center justify-center px-2 text-center w-full">
          {editing ? (
            <div className="flex items-center gap-1 w-full">
              <input
                value={draft}
                onChange={(e) => setDraft(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === "Enter") { onUpdate(draft); setEditing(false); }
                  if (e.key === "Escape") { setDraft(ln.node.label); setEditing(false); }
                }}
                autoFocus
                className="flex-1 min-w-0 text-xs px-1 py-0.5 rounded border bg-background"
              />
              <button onClick={() => { onUpdate(draft); setEditing(false); }}
                className="p-0.5 rounded hover:bg-muted"><Check className="h-3 w-3 text-emerald-600" /></button>
              <button onClick={() => { setDraft(ln.node.label); setEditing(false); }}
                className="p-0.5 rounded hover:bg-muted"><X className="h-3 w-3 text-muted-foreground" /></button>
            </div>
          ) : customBody !== null && customBody !== undefined ? (
            customBody
          ) : (
            <>
              <p className="text-xs font-semibold leading-tight line-clamp-2 break-words">{ln.node.label}</p>
              {ln.node.meta?.description && (
                <p className="text-[10px] text-muted-foreground leading-tight line-clamp-1 mt-0.5">
                  {ln.node.meta.description}
                </p>
              )}
            </>
          )}
        </div>
      </div>

      {locked && (
        <span className="absolute top-1 right-1 text-muted-foreground"><Lock className="h-3 w-3" /></span>
      )}

      {/* over-limit warning chip — appears when a parent has more children
          than its current maxChildren allows. Non-blocking; informational. */}
      {overLimit && maxChildren != null && (
        <span
          title={\`This node has \${childCount} children but the limit is \${maxChildren}. Remove \${childCount - maxChildren} to comply.\`}
          className="absolute -top-2 -right-2 z-20 inline-flex items-center gap-0.5 rounded-full border border-amber-500/40 bg-amber-500/10 px-1.5 py-0.5 text-[9px] font-semibold text-amber-700 dark:text-amber-400 shadow-sm"
        >
          <AlertTriangle className="h-2.5 w-2.5" />
          {childCount}/{maxChildren}
        </span>
      )}

      {/* hover toolbar */}
      {editable && !editing && !locked && (
        <div className="absolute -bottom-3 left-1/2 -translate-x-1/2 z-10 flex items-center gap-0.5 rounded-md border border-border bg-background text-foreground shadow-sm opacity-0 group-hover:opacity-100 transition-opacity">
          {blueprintOptions && blueprintOptions.length > 0 ? (
            <BlueprintPicker
              options={blueprintOptions}
              disabled={!canAddChild}
              maxChildren={maxChildren}
              childCount={childCount}
              onPick={(id) => onAdd(id)}
            />
          ) : (
            <button
              onClick={(e) => { e.stopPropagation(); if (canAddChild) onAdd(); }}
              disabled={!canAddChild}
              title={canAddChild ? "Add child" : maxChildren != null ? \`Max \${maxChildren} children reached (\${childCount}/\${maxChildren})\` : "Add disabled"}
              className="h-6 w-6 grid place-items-center hover:bg-muted disabled:opacity-30 disabled:cursor-not-allowed"
            >
              <Plus className="h-3 w-3" />
            </button>
          )}
          {canEdit && (
            <button onClick={(e) => { e.stopPropagation(); setEditing(true); }}
              title="Rename"
              className="h-6 w-6 grid place-items-center hover:bg-muted">
              <Pencil className="h-3 w-3" />
            </button>
          )}
          {!isRoot && canDelete && (
            <button onClick={(e) => { e.stopPropagation(); onRemove(); }}
              title="Remove"
              className="h-6 w-6 grid place-items-center hover:bg-muted text-destructive">
              <Trash2 className="h-3 w-3" />
            </button>
          )}
        </div>
      )}

      {/* position controls — sibling reorder without DnD */}
      {showPositionControls && !isRoot && !editing && (
        <div className={cn(
          "absolute z-10 flex items-center gap-0.5 rounded-md border border-border bg-background shadow-sm opacity-0 group-hover:opacity-100 transition-opacity",
          dropAxis === "horizontal"
            ? "-top-3 left-1/2 -translate-x-1/2"
            : "top-1/2 -translate-y-1/2 -right-3",
        )}>
          <button
            onClick={(e) => { e.stopPropagation(); if (canMovePrev) onReorder(-1); }}
            disabled={!canMovePrev}
            title="Move earlier"
            className="h-6 w-6 grid place-items-center hover:bg-muted disabled:opacity-30 disabled:cursor-not-allowed"
          >
            {dropAxis === "horizontal" ? <ChevronUp className="h-3 w-3" /> : <ChevronLeft className="h-3 w-3" />}
          </button>
          <button
            onClick={(e) => { e.stopPropagation(); if (canMoveNext) onReorder(1); }}
            disabled={!canMoveNext}
            title="Move later"
            className="h-6 w-6 grid place-items-center hover:bg-muted disabled:opacity-30 disabled:cursor-not-allowed"
          >
            {dropAxis === "horizontal" ? <ChevronDown className="h-3 w-3" /> : <ChevronRight className="h-3 w-3" />}
          </button>
        </div>
      )}

    </div>
  );
}


/**
 * Typed add-child picker — used when a node's \`meta.allowedChildren\` resolves
 * to one or more blueprints from \`config.nodeBlueprints\`. Click the + button
 * to open the menu; pick a blueprint to insert a new child of that type with
 * the blueprint's default label and meta.
 */
function BlueprintPicker({
  options, disabled, maxChildren, childCount, onPick,
}: {
  options: { id: string; label: string; description?: string }[];
  disabled: boolean;
  maxChildren: number | null;
  childCount: number;
  onPick: (id: string) => void;
}) {
  const [open, setOpen] = useState(false);
  const wrapRef = useRef<HTMLDivElement | null>(null);
  useEffect(() => {
    if (!open) return;
    const onDown = (e: PointerEvent) => {
      if (!wrapRef.current?.contains(e.target as Node)) setOpen(false);
    };
    window.addEventListener("pointerdown", onDown);
    return () => window.removeEventListener("pointerdown", onDown);
  }, [open]);
  const title = disabled
    ? maxChildren != null
      ? \`Max \${maxChildren} children reached (\${childCount}/\${maxChildren})\`
      : "Add disabled"
    : "Add child";
  return (
    <div ref={wrapRef} className="relative">
      <button
        onClick={(e) => { e.stopPropagation(); if (!disabled) setOpen((v) => !v); }}
        disabled={disabled}
        title={title}
        className="h-6 w-6 grid place-items-center hover:bg-muted disabled:opacity-30 disabled:cursor-not-allowed"
      >
        <Plus className="h-3 w-3" />
      </button>
      {open && (
        <div
          onPointerDown={(e) => e.stopPropagation()}
          className="absolute left-1/2 top-full z-50 mt-1 -translate-x-1/2 min-w-[180px] rounded-md border border-border bg-popover text-popover-foreground shadow-md overflow-hidden"
        >
          <div className="px-2 py-1 text-[9px] font-semibold uppercase tracking-wider text-muted-foreground border-b border-border">
            Add child
          </div>
          {options.map((o) => (
            <button
              key={o.id}
              onClick={(e) => { e.stopPropagation(); onPick(o.id); setOpen(false); }}
              className="w-full text-left px-2 py-1.5 text-xs hover:bg-muted transition-colors"
            >
              <div className="font-medium">{o.label}</div>
              {o.description && (
                <div className="text-[10px] text-muted-foreground leading-tight">{o.description}</div>
              )}
            </button>
          ))}
        </div>
      )}
    </div>
  );
}
`;
const components_tree_treeLayoutRaw = `/**
 * Pure layout algorithms for the TreeCanvas. No external graph library —
 * every layout produces an \`id → { x, y, width, height }\` map plus a list of
 * connector segments.
 *
 * Coordinates are in canvas-pixel space; the renderer wraps them in a
 * pan/zoomable SVG + absolutely-positioned DOM nodes.
 */
import type { TreeLayout, TreeNode } from "./types";

export interface LayoutNode {
  id: string;
  node: TreeNode;
  parentId: string | null;
  depth: number;
  x: number;
  y: number;
  width: number;
  height: number;
}

export interface LayoutEdge {
  fromId: string;
  toId: string;
  /** Connector path — the renderer chooses how to stroke it. */
  points: { x: number; y: number }[];
  /** Optional label rendered at the midpoint of the edge. */
  label?: string;
}

export interface LayoutResult {
  nodes: LayoutNode[];
  edges: LayoutEdge[];
  width: number;
  height: number;
}

interface LayoutOpts {
  siblingGap: number;
  levelGap: number;
  nodeWidth: number;
  nodeHeight: number;
}

/* ------------------------------------------------------------------ */
/*  Shared helpers                                                     */
/* ------------------------------------------------------------------ */

function flattenWithDepth(root: TreeNode): { node: TreeNode; depth: number; parentId: string | null }[] {
  const out: { node: TreeNode; depth: number; parentId: string | null }[] = [];
  const walk = (n: TreeNode, d: number, p: string | null) => {
    out.push({ node: n, depth: d, parentId: p });
    n.children?.forEach((c) => walk(c, d + 1, n.id));
  };
  walk(root, 0, null);
  return out;
}

/** Returns the number of leaves under a node — used to size sibling spans. */
function leafCount(n: TreeNode): number {
  if (!n.children?.length) return 1;
  return n.children.reduce((s, c) => s + leafCount(c), 0);
}

/* ------------------------------------------------------------------ */
/*  Horizontal — root on the left, generations marching right.         */
/*  This produces the "pipeline / workflow" feel from the reference.   */
/* ------------------------------------------------------------------ */

function layoutHorizontal(root: TreeNode, o: LayoutOpts): LayoutResult {
  const nodes: LayoutNode[] = [];
  const edges: LayoutEdge[] = [];
  const colWidth = o.nodeWidth + o.levelGap;

  // First pass: compute Y center per node by giving each leaf a row, then
  // averaging children's centers up the tree.
  const yCenter = new Map<string, number>();
  let leafCursor = 0;
  const rowHeight = o.nodeHeight + o.siblingGap;
  const computeY = (n: TreeNode): number => {
    if (!n.children?.length) {
      const y = leafCursor * rowHeight + o.nodeHeight / 2;
      leafCursor++;
      yCenter.set(n.id, y);
      return y;
    }
    const childYs = n.children.map(computeY);
    const y = (childYs[0] + childYs[childYs.length - 1]) / 2;
    yCenter.set(n.id, y);
    return y;
  };
  computeY(root);

  flattenWithDepth(root).forEach(({ node, depth, parentId }) => {
    const cy = yCenter.get(node.id) ?? 0;
    const x = depth * colWidth;
    const y = cy - o.nodeHeight / 2;
    nodes.push({ id: node.id, node, parentId, depth, x, y, width: o.nodeWidth, height: o.nodeHeight });
    if (parentId) {
      const parent = nodes.find((n) => n.id === parentId)!;
      edges.push({
        fromId: parentId, toId: node.id,
        points: [
          { x: parent.x + parent.width, y: parent.y + parent.height / 2 },
          { x: x, y: y + o.nodeHeight / 2 },
        ],
      });
    }
  });

  const width = (Math.max(...nodes.map((n) => n.depth)) + 1) * colWidth;
  const height = leafCursor * rowHeight;
  return { nodes, edges, width, height };
}

/* ------------------------------------------------------------------ */
/*  Vertical — top → bottom org chart                                  */
/* ------------------------------------------------------------------ */

function layoutVertical(root: TreeNode, o: LayoutOpts): LayoutResult {
  const nodes: LayoutNode[] = [];
  const edges: LayoutEdge[] = [];
  const rowHeight = o.nodeHeight + o.levelGap;
  const colWidth = o.nodeWidth + o.siblingGap;

  const xCenter = new Map<string, number>();
  let leafCursor = 0;
  const computeX = (n: TreeNode): number => {
    if (!n.children?.length) {
      const x = leafCursor * colWidth + o.nodeWidth / 2;
      leafCursor++;
      xCenter.set(n.id, x);
      return x;
    }
    const childXs = n.children.map(computeX);
    const x = (childXs[0] + childXs[childXs.length - 1]) / 2;
    xCenter.set(n.id, x);
    return x;
  };
  computeX(root);

  flattenWithDepth(root).forEach(({ node, depth, parentId }) => {
    const cx = xCenter.get(node.id) ?? 0;
    const y = depth * rowHeight;
    const x = cx - o.nodeWidth / 2;
    nodes.push({ id: node.id, node, parentId, depth, x, y, width: o.nodeWidth, height: o.nodeHeight });
    if (parentId) {
      const parent = nodes.find((n) => n.id === parentId)!;
      edges.push({
        fromId: parentId, toId: node.id,
        points: [
          { x: parent.x + parent.width / 2, y: parent.y + parent.height },
          { x: x + o.nodeWidth / 2, y: y },
        ],
      });
    }
  });

  const width = leafCursor * colWidth;
  const height = (Math.max(...nodes.map((n) => n.depth)) + 1) * rowHeight;
  return { nodes, edges, width, height };
}

/* ------------------------------------------------------------------ */
/*  Radial — root in centre, descendants on concentric rings           */
/* ------------------------------------------------------------------ */

function layoutRadial(root: TreeNode, o: LayoutOpts): LayoutResult {
  const nodes: LayoutNode[] = [];
  const edges: LayoutEdge[] = [];
  const ringStep = o.nodeWidth + o.levelGap;
  const totalLeaves = leafCount(root);
  const TAU = Math.PI * 2;

  // Assign each node an angular slice proportional to its leaf count.
  const sliceMap = new Map<string, { start: number; end: number }>();
  sliceMap.set(root.id, { start: 0, end: TAU });
  const assign = (n: TreeNode) => {
    const slice = sliceMap.get(n.id)!;
    if (!n.children?.length) return;
    let cursor = slice.start;
    const span = slice.end - slice.start;
    for (const c of n.children) {
      const portion = span * (leafCount(c) / leafCount(n));
      sliceMap.set(c.id, { start: cursor, end: cursor + portion });
      cursor += portion;
      assign(c);
    }
  };
  assign(root);

  let maxR = 0;
  flattenWithDepth(root).forEach(({ node, depth, parentId }) => {
    const slice = sliceMap.get(node.id)!;
    const angle = (slice.start + slice.end) / 2;
    const r = depth === 0 ? 0 : depth * ringStep;
    maxR = Math.max(maxR, r);
    const cx = r * Math.cos(angle - Math.PI / 2);
    const cy = r * Math.sin(angle - Math.PI / 2);
    nodes.push({
      id: node.id, node, parentId, depth,
      x: cx - o.nodeWidth / 2, y: cy - o.nodeHeight / 2,
      width: o.nodeWidth, height: o.nodeHeight,
    });
    if (parentId) {
      const p = nodes.find((n) => n.id === parentId)!;
      edges.push({
        fromId: parentId, toId: node.id,
        points: [
          { x: p.x + p.width / 2, y: p.y + p.height / 2 },
          { x: cx, y: cy },
        ],
      });
    }
  });

  // Translate so coords are >= 0
  const offset = maxR + o.nodeWidth;
  nodes.forEach((n) => { n.x += offset; n.y += offset; });
  edges.forEach((e) => e.points.forEach((p) => { p.x += offset; p.y += offset; }));
  const size = offset * 2;
  // suppress unused warning
  void totalLeaves;
  return { nodes, edges, width: size, height: size };
}

/* ------------------------------------------------------------------ */
/*  Mindmap — root in middle, branches alternate left/right            */
/* ------------------------------------------------------------------ */

function layoutMindmap(root: TreeNode, o: LayoutOpts): LayoutResult {
  const left: TreeNode = { id: "__l", label: "", children: [] };
  const right: TreeNode = { id: "__r", label: "", children: [] };
  (root.children ?? []).forEach((c, i) => {
    if (i % 2 === 0) right.children!.push(c);
    else left.children!.push(c);
  });

  const r = layoutHorizontal({ ...root, children: right.children }, o);
  const l = layoutHorizontal({ ...root, children: left.children }, o);

  // Mirror left side around root x = 0
  const lNodes = l.nodes.filter((n) => n.id !== root.id).map((n) => ({
    ...n,
    x: -n.x - n.width,
  }));
  const lEdges = l.edges.map((e) => ({
    ...e,
    points: e.points.map((p) => ({ x: -p.x, y: p.y })),
  }));

  const allNodes: LayoutNode[] = [
    ...r.nodes,
    ...lNodes,
  ];
  const allEdges: LayoutEdge[] = [...r.edges, ...lEdges];

  const minX = Math.min(0, ...allNodes.map((n) => n.x));
  const maxX = Math.max(...allNodes.map((n) => n.x + n.width));
  const minY = Math.min(...allNodes.map((n) => n.y));
  const maxY = Math.max(...allNodes.map((n) => n.y + n.height));

  allNodes.forEach((n) => { n.x -= minX; n.y -= minY; });
  allEdges.forEach((e) => e.points.forEach((p) => { p.x -= minX; p.y -= minY; }));

  return { nodes: allNodes, edges: allEdges, width: maxX - minX, height: maxY - minY };
}

/* ------------------------------------------------------------------ */
/*  Org — vertical with extra spacing + boxed connectors               */
/* ------------------------------------------------------------------ */

function layoutOrg(root: TreeNode, o: LayoutOpts): LayoutResult {
  return layoutVertical(root, {
    ...o,
    siblingGap: o.siblingGap + 24,
    levelGap: o.levelGap + 28,
  });
}

/* ------------------------------------------------------------------ */
/*  Public entry                                                       */
/* ------------------------------------------------------------------ */

export function computeLayout(
  root: TreeNode,
  layout: TreeLayout,
  opts: Partial<LayoutOpts> = {},
): LayoutResult {
  const merged: LayoutOpts = {
    siblingGap: opts.siblingGap ?? 24,
    levelGap: opts.levelGap ?? 96,
    nodeWidth: opts.nodeWidth ?? 168,
    nodeHeight: opts.nodeHeight ?? 64,
  };
  let result: LayoutResult;
  switch (layout) {
    case "horizontal": result = layoutHorizontal(root, merged); break;
    case "vertical":   result = layoutVertical(root, merged); break;
    case "radial":     result = layoutRadial(root, merged); break;
    case "mindmap":    result = layoutMindmap(root, merged); break;
    case "org":        result = layoutOrg(root, merged); break;
  }
  // Decorate edges with the child node's \`meta.edgeLabel\` so the renderer can
  // draw "More than $50K" / "Good / Bad" style midpoint pills (n8n / mindmap).
  const labelByChildId = new Map<string, string>();
  const collect = (n: TreeNode) => {
    if (n.meta?.edgeLabel) labelByChildId.set(n.id, n.meta.edgeLabel);
    n.children?.forEach(collect);
  };
  collect(root);
  result.edges = result.edges.map((e) =>
    labelByChildId.has(e.toId) ? { ...e, label: labelByChildId.get(e.toId) } : e,
  );
  return result;
}
`;
const components_tree_typesRaw = `/**
 * Public types for the TreeCanvas engine.
 *
 * The tree is a recursive \`TreeNode\` structure. Layouts are computed purely
 * from this data — no external graph library is needed.
 */

import type { ReactNode } from "react";

export type TreeLayout =
  | "horizontal"   // root → leaves left-to-right (workflow / pipeline style, like the reference screenshot)
  | "vertical"     // root → leaves top-to-bottom (classic org chart)
  | "radial"       // root in centre, descendants on concentric rings
  | "mindmap"      // root in centre, branches alternate left/right
  | "org";         // boxed org-chart with sibling spread + thicker connectors

export type NodeShape = "rect" | "rounded" | "pill" | "diamond" | "circle";

/* ----------------------------------------------------------------
 * Render-function node API (shadcn DataTable cell-def style).
 * ----------------------------------------------------------------
 * Two-level resolution at render time:
 *   1. node.meta.render — per-node override   (highest priority)
 *   2. config.renderNode — flow-wide reusable renderer
 *   3. built-in default body — label + optional description
 */
export interface NodeRenderContext {
  node: TreeNode;
  childCount: number;
  depth: number;
  isRoot: boolean;
}
export type NodeRenderer = (ctx: NodeRenderContext) => ReactNode;

/** Per-node visual / behavioural metadata. Optional everywhere. */
export interface TreeNodeMeta {
  badge?: string;
  badgeColor?: string;        // tailwind / css color token (eg "primary")
  description?: string;
  icon?: string;              // lucide name; renderer maps strings → component
  color?: string;             // accent color for node frame
  shape?: NodeShape;
  /** Marks this node as locked — disables add/edit/remove on it. */
  locked?: boolean;
  /** Optional tags used by the GraphToolbar for chip filters. */
  tags?: string[];
  /** Sortable numeric / string key used by the toolbar's "custom" sort. */
  sortKey?: number | string;
  /** Per-node row dataset — exposed via the NodeDataTable dialog. */
  dataset?: import("@/components/graph/types").NodeDataset;
  /** Whitelist of feature toggles enabled on this node (used by Flow Builder). */
  features?: string[];
  /** Max number of children this node may have. \`null\`/undefined = unlimited. */
  maxChildren?: number | null;
  /** Label rendered on the edge from this node's parent → this node (n8n / mindmap style). */
  edgeLabel?: string;
  /** What happens when this node is clicked in the Preview. */
  action?: TreeNodeAction;
  /** Free-position offset (px) applied on top of the auto layout. Set via Alt+drag. */
  positionOffset?: { dx: number; dy: number };
  /** Per-node permission overrides — only effective when the global config flag is true. */
  permissions?: { add?: boolean; edit?: boolean; delete?: boolean; drag?: boolean };
  /**
   * Per-node restriction on which drop modes are valid when other nodes are
   * dragged onto this one. Missing keys inherit from \`TreeCanvasConfig.dragModes\`
   * (which itself defaults to all three on).
   */
  dragModes?: { child?: boolean; before?: boolean; after?: boolean };
  /**
   * Per-instance whitelist of blueprint ids that may be added as children of
   * this node. Used together with \`TreeCanvasConfig.nodeBlueprints\`. When set
   * (even to an empty array), the add-child button opens a typed picker
   * instead of inserting a generic "New Step" node.
   */
  allowedChildren?: string[];
  /** This node's blueprint id (informational — surfaced in tooling). */
  blueprintId?: string;
  /** Per-node render function — full control over this node's body. */
  render?: NodeRenderer;
}

/**
 * A node blueprint — defines a reusable node "type" (trigger, action, etc.)
 * with a default label and meta. Referenced by id from \`meta.allowedChildren\`
 * to gate which child types can be added under each node.
 */
export interface NodeBlueprint {
  /** Default label given to new nodes of this blueprint. */
  label: string;
  /** Default meta applied to new nodes of this blueprint. */
  meta?: Partial<TreeNodeMeta>;
  /** Optional human description shown in the add-child picker. */
  description?: string;
}

export type TreeNodeAction =
  | { kind: "none" }
  | { kind: "dialog"; title?: string; body?: string }
  | { kind: "drawer"; title?: string; body?: string }
  | { kind: "panel"; title?: string; body?: string }
  | { kind: "route"; href: string; label?: string }
  | { kind: "table-dialog"; title?: string }
  | { kind: "table-panel"; title?: string };


export interface TreeNode {
  id: string;
  label: string;
  children?: TreeNode[];
  meta?: TreeNodeMeta;
}

/** Configuration that drives a TreeCanvas instance — lives next to data. */
export interface TreeCanvasConfig {
  title: string;
  subtitle?: string;
  layout: TreeLayout;
  /** Spacing between siblings (px). */
  siblingGap?: number;
  /** Spacing between depth levels (px). */
  levelGap?: number;
  /** Default node visual style. */
  nodeShape?: NodeShape;
  /** Show a small +/- button on each node (interactive editing). */
  editable?: boolean;
  /** Show the level label above each level (eg "PICK", "PACK"). */
  showLevelLabels?: boolean;
  /** Connector style. */
  connector?: "straight" | "stepped" | "curved" | "dashed";
  /** Enable pan + zoom on the canvas viewport. */
  panZoom?: boolean;
  /** Background pattern. */
  background?: "none" | "dots" | "grid" | "cross" | "diagonal" | "blueprint";
  /** Custom min height for the canvas (px). */
  minHeight?: number;
  /** Enable drag-and-drop reparenting / sibling re-ordering. */
  draggable?: boolean;
  /**
   * Flip the drop indicator axis: horizontal flows show top/bottom drop
   * zones, vertical flows show left/right. Independent of any other flag.
   */
  siblingDndAxisInverted?: boolean;
  /** Show ◀ ▶ / ▲ ▼ chevrons on each node so users can re-order without dragging. */
  showPositionControls?: boolean;
  /** When true, hides every interactive affordance (add / rename / remove / drag). */
  readOnly?: boolean;
  /** Direction — "rtl" mirrors horizontal layouts. Defaults to document.dir or "ltr". */
  dir?: "ltr" | "rtl";
  /** Enable free positioning via Alt+drag — persists \`meta.positionOffset\` on a node. */
  allowFreePosition?: boolean;
  /** Global permission gates. A node's \`meta.permissions\` can only further restrict. */
  allowAdd?: boolean;
  allowEdit?: boolean;
  allowDelete?: boolean;
  allowDrag?: boolean;
  /**
   * Global drop-mode gate. A node's \`meta.dragModes\` can further restrict per-node.
   * Defaults to all three on. Set any to \`false\` to forbid that drop mode flow-wide.
   */
  dragModes?: { child?: boolean; before?: boolean; after?: boolean };
  /** Show the GraphToolbar (search / sort / filter) above the canvas in Preview. */
  showToolbar?: boolean;
  /**
   * Flow-wide reusable node renderer (shadcn DataTable column-def style).
   * Every node uses this unless it sets its own \`meta.render\`. When neither
   * is set, the built-in default body (label + description) is used.
   */
  renderNode?: NodeRenderer;
  /**
   * Registry of node blueprints (= node "types"). When set, nodes whose
   * \`meta.allowedChildren\` references blueprint ids show a typed picker on
   * their add-child button instead of inserting a generic node. Cleaner than
   * declaring \`allowedChildren\` per-instance — define the rules once here,
   * reference them by id everywhere.
   */
  nodeBlueprints?: Record<string, NodeBlueprint>;
}

export type TreeMoveMode = "child" | "before" | "after";

/** Event payloads — mirrored as separate handlers on the public component. */
export interface TreeNodeAddEvent {
  parent: TreeNode;
  newNode: TreeNode;
  tree: TreeNode;
}
export interface TreeNodeUpdateEvent {
  node: TreeNode;
  prev: TreeNode;
  tree: TreeNode;
}
export interface TreeNodeRemoveEvent {
  node: TreeNode;
  parent: TreeNode | null;
  tree: TreeNode;
}

/** Fired when a node is dragged onto another node and dropped. */
export interface TreeNodeMoveEvent {
  node: TreeNode;
  /** Where the node lived before the move. */
  prev: { parentId: string | null; index: number };
  /** Where the node was dropped. */
  next: { parentId: string; index: number; mode: TreeMoveMode };
  tree: TreeNode;
}

export interface TreeCanvasHandlers {
  onNodeAdd?: (event: TreeNodeAddEvent) => void;
  onNodeUpdate?: (event: TreeNodeUpdateEvent) => void;
  onNodeRemove?: (event: TreeNodeRemoveEvent) => void;
  onNodeMove?: (event: TreeNodeMoveEvent) => void;
  /** Fired when a node body is clicked (no drag). Useful for opening detail panels. */
  onNodeClick?: (node: TreeNode) => void;
}
`;
const components_graph_typesRaw = `/**
 * Shared types for the graph lib — used by FlowCanvas, FlowBuilder and the
 * search/sort/filter toolbar that overlays both /tree-builder and /flow.
 */

export type GraphSortDir = "asc" | "desc";

export interface GraphFilterState {
  search: string;
  /** Sort siblings of every parent by this metric. */
  sort: { field: "label" | "depth" | "children" | "custom" | "none"; dir: GraphSortDir };
  /** Active tag filters — a node passes if it has at least one. */
  tags: string[];
  /** Predicate name keyed by \`predicates\` map passed in by the consumer. */
  predicate?: string;
  /** Hide non-matches entirely instead of dimming. */
  mode: "dim" | "hide";
}

export const defaultGraphFilter: GraphFilterState = {
  search: "",
  sort: { field: "none", dir: "asc" },
  tags: [],
  predicate: undefined,
  mode: "dim",
};

/** Generic dataset attached to a node (e.g. enrolled students). */
export interface NodeDatasetColumn {
  key: string;
  label: string;
  type?: "text" | "number" | "date" | "badge";
}

export interface NodeDataset {
  title?: string;
  columns: NodeDatasetColumn[];
  rows: Record<string, unknown>[];
}

/** A single named predicate the toolbar exposes (e.g. "Top 5 scorers"). */
export interface GraphPredicate<T = unknown> {
  id: string;
  label: string;
  description?: string;
  /** Returns true if the node should be kept. */
  test: (ctx: { label: string; tags: string[]; depth: number; meta: T }) => boolean;
}
`;
const components_graph_indexRaw = `/**
 * src/lib/graph — shared utilities for tree + flow canvases.
 *
 * Provides a search/sort/filter toolbar, a per-node dataset table, and the
 * underlying filter hook. Used by /tree-builder, /flow and /flow-builder.
 */
export {
  defaultGraphFilter,
  type NodeDataset,
  type GraphSortDir,
  type GraphPredicate,
  type GraphFilterState,
  type NodeDatasetColumn,
} from "./types";
export { GraphToolbar } from "./GraphToolbar";
export { useGraphFilter } from "./useGraphFilter";
export type { FilterableNode, FilterResult } from "./useGraphFilter";
`;
const components_graph_GraphToolbarRaw = `/**
 * Generic toolbar that sits above any tree/flow canvas.
 * Provides search, sort, tag chips, named predicates, and a hide/dim toggle.
 */
import { Search, ArrowUpDown, EyeOff, Eye, X, Info } from "lucide-react";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  Select, SelectContent, SelectItem, SelectTrigger, SelectValue,
} from "@/components/ui/select";
import { cn } from "@/lib/utils";
import type { GraphFilterState, GraphPredicate } from "./types";

interface Props {
  filter: GraphFilterState;
  onChange: (next: GraphFilterState) => void;
  allTags: string[];
  predicates?: GraphPredicate[];
  matched: number;
  total: number;
  className?: string;
  /** Hide individual controls when the consumer wants a slimmer toolbar. */
  showSearch?: boolean;
  showSort?: boolean;
  showFilter?: boolean;
}

export function GraphToolbar({
  filter, onChange, allTags, predicates = [], matched, total, className,
  showSearch = true, showSort = true, showFilter = true,
}: Props) {
  const update = <K extends keyof GraphFilterState>(key: K, value: GraphFilterState[K]) =>
    onChange({ ...filter, [key]: value });

  const toggleTag = (tag: string) => {
    update("tags", filter.tags.includes(tag) ? filter.tags.filter((t) => t !== tag) : [...filter.tags, tag]);
  };

  const hasActive = filter.search || filter.tags.length > 0 || filter.predicate || filter.sort.field !== "none";

  return (
    <div className={cn("flex flex-col gap-2 rounded-lg border border-border bg-card p-2", className)}>
      <div className="flex flex-wrap items-center gap-2">
        {showSearch && (
        <div className="relative flex-1 min-w-[180px]" title="Hides or dims nodes whose label doesn't contain this text.">
          <Search className="absolute left-2 top-1/2 -translate-y-1/2 h-3.5 w-3.5 text-muted-foreground" />
          <Input
            value={filter.search}
            onChange={(e) => update("search", e.target.value)}
            placeholder="Search nodes…"
            className="h-8 pl-7 text-xs"
          />
        </div>
        )}

        {showSort && <>
        <Select
          value={filter.sort.field}
          onValueChange={(v) => update("sort", { ...filter.sort, field: v as GraphFilterState["sort"]["field"] })}
        >
          <SelectTrigger className="h-8 w-[140px] text-xs" title="Re-orders the children of every parent by this metric.">
            <ArrowUpDown className="h-3 w-3 mr-1" />
            <SelectValue placeholder="Sort by" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="none">No sort</SelectItem>
            <SelectItem value="label">Label (A–Z)</SelectItem>
            <SelectItem value="children">Children count</SelectItem>
            <SelectItem value="depth">Subtree size</SelectItem>
            <SelectItem value="custom">Custom (meta.sortKey)</SelectItem>
          </SelectContent>
        </Select>
        <Button
          variant="outline"
          size="sm"
          className="h-8 px-2 text-xs"
          title="Toggle ascending / descending"
          onClick={() => update("sort", { ...filter.sort, dir: filter.sort.dir === "asc" ? "desc" : "asc" })}
          disabled={filter.sort.field === "none"}
        >
          {filter.sort.dir === "asc" ? "↑" : "↓"}
        </Button>
        </>}

        {showFilter && predicates.length > 0 && (
          <Select
            value={filter.predicate ?? "__none"}
            onValueChange={(v) => update("predicate", v === "__none" ? undefined : v)}
          >
            <SelectTrigger className="h-8 w-[180px] text-xs" title="Predicate filter — only nodes matching the chosen rule pass.">
              <SelectValue placeholder="Smart filter" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="__none">No filter</SelectItem>
              {predicates.map((p) => (
                <SelectItem key={p.id} value={p.id}>{p.label}</SelectItem>
              ))}
            </SelectContent>
          </Select>
        )}

        {showFilter && <Button
          variant="outline"
          size="sm"
          className="h-8 px-2 text-xs gap-1"
          title={filter.mode === "dim" ? "Dim mode: non-matches are faded but stay in place. Click to switch to Hide." : "Hide mode: non-matches are removed from the tree. Click to switch to Dim."}
          onClick={() => update("mode", filter.mode === "dim" ? "hide" : "dim")}
        >
          {filter.mode === "dim" ? <Eye className="h-3 w-3" /> : <EyeOff className="h-3 w-3" />}
          {filter.mode === "dim" ? "Dim" : "Hide"}
        </Button>}

        <span className="text-[10px] text-muted-foreground tabular-nums px-1">
          {matched}/{total}
        </span>

        {hasActive && (
          <Button
            variant="ghost"
            size="sm"
            className="h-8 px-2 text-xs gap-1"
            onClick={() => onChange({ search: "", sort: { field: "none", dir: "asc" }, tags: [], mode: filter.mode })}
          >
            <X className="h-3 w-3" /> Clear
          </Button>
        )}
      </div>

      {showFilter && allTags.length > 0 && (
        <div className="flex flex-wrap items-center gap-1">
          <span className="text-[10px] uppercase tracking-widest text-muted-foreground mr-1">Tags</span>
          {allTags.map((tag) => (
            <button
              key={tag}
              onClick={() => toggleTag(tag)}
              title={\`Filter to nodes tagged "\${tag}"\`}
              className={cn(
                "px-2 py-0.5 rounded-full text-[10px] font-medium border transition-colors",
                filter.tags.includes(tag)
                  ? "bg-primary text-primary-foreground border-primary"
                  : "bg-background text-muted-foreground border-border hover:text-foreground",
              )}
            >
              {tag}
            </button>
          ))}
        </div>
      )}

      {showFilter && filter.predicate && predicates.find((p) => p.id === filter.predicate)?.description && (
        <Badge variant="secondary" className="text-[10px] w-fit">
          {predicates.find((p) => p.id === filter.predicate)!.description}
        </Badge>
      )}

      {/* Always-visible helptext so users know what each control does. */}
      <p className="flex items-start gap-1 text-[10px] text-muted-foreground leading-snug">
        <Info className="h-3 w-3 mt-0.5 shrink-0" />
        <span>
          {showSearch && <><b>Search</b> matches node labels. </>}
          {showSort && <><b>Sort</b> re-orders each parent's children. </>}
          {showFilter && <><b>Tags / smart filter</b> mark which nodes match; </>}
          {showFilter && <><b>Dim</b> fades non-matches in place, <b>Hide</b> removes them from the tree.</>}
        </span>
      </p>
    </div>
  );
}
`;
const components_graph_useGraphFilterRaw = `/**
 * Pure tree filter / sort / search hook. Works with the TreeCanvas TreeNode
 * shape (\`{ id, label, meta?, children? }\`) but stays type-agnostic so it can
 * power the flow builder, tree variants and any future graph view.
 */
import { useMemo } from "react";
import type { GraphFilterState, GraphPredicate } from "./types";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export interface FilterableNode {
  id: string;
  label: string;
  meta?: any;
  children?: FilterableNode[];
}

export interface FilterResult<N extends FilterableNode> {
  /** Tree with non-matching siblings stripped (mode = "hide"). */
  tree: N;
  /** Set of node ids that match the filter. */
  matches: Set<string>;
  /** Total node count (pre-filter) and matched count. */
  stats: { total: number; matched: number };
  /** All distinct tags found in the tree — handy for chip toolbars. */
  allTags: string[];
}

function walk<N extends FilterableNode>(n: N, fn: (n: N, depth: number) => void, depth = 0): void {
  fn(n, depth);
  n.children?.forEach((c) => walk(c as N, fn, depth + 1));
}

function nodeTags(n: FilterableNode): string[] {
  return Array.isArray(n.meta?.tags) ? (n.meta!.tags as string[]) : [];
}

function sortChildren<N extends FilterableNode>(
  children: N[],
  filter: GraphFilterState,
  predicateMap: Record<string, GraphPredicate>,
): N[] {
  if (filter.sort.field === "none") return children;
  const dir = filter.sort.dir === "asc" ? 1 : -1;
  const arr = [...children];
  arr.sort((a, b) => {
    let av: number | string = "";
    let bv: number | string = "";
    switch (filter.sort.field) {
      case "label": av = a.label; bv = b.label; break;
      case "depth": av = countDescendants(a); bv = countDescendants(b); break;
      case "children": av = a.children?.length ?? 0; bv = b.children?.length ?? 0; break;
      case "custom":
        av = (a.meta?.sortKey as number | string) ?? 0;
        bv = (b.meta?.sortKey as number | string) ?? 0;
        break;
    }
    if (typeof av === "number" && typeof bv === "number") return (av - bv) * dir;
    return String(av).localeCompare(String(bv)) * dir;
  });
  // suppress unused predicateMap warning
  void predicateMap;
  return arr;
}

function countDescendants(n: FilterableNode): number {
  let total = 0;
  walk(n, (x) => { if (x !== n) total += 1; });
  return total;
}

export function useGraphFilter<N extends FilterableNode>(
  tree: N,
  filter: GraphFilterState,
  predicates: GraphPredicate[] = [],
): FilterResult<N> {
  return useMemo(() => {
    const predicateMap = Object.fromEntries(predicates.map((p) => [p.id, p]));
    const activePredicate = filter.predicate ? predicateMap[filter.predicate] : undefined;
    const search = filter.search.trim().toLowerCase();

    const matches = new Set<string>();
    let total = 0;
    const allTagsSet = new Set<string>();

    walk(tree, (n, depth) => {
      total += 1;
      nodeTags(n).forEach((t) => allTagsSet.add(t));
      const tags = nodeTags(n);
      const passSearch = search.length === 0 || n.label.toLowerCase().includes(search);
      const passTags = filter.tags.length === 0 || filter.tags.some((t) => tags.includes(t));
      const passPred = activePredicate
        ? activePredicate.test({ label: n.label, tags, depth, meta: n.meta as unknown })
        : true;
      if (passSearch && passTags && passPred) matches.add(n.id);
    });

    /** When mode = "hide", strip non-matching nodes — but always keep the root
     *  and any ancestor of a match so the surviving subtree stays reachable. */
    const ancestorsOfMatch = new Set<string>();
    const collectAncestors = (n: N, chain: N[]) => {
      const next = [...chain, n];
      if (matches.has(n.id)) next.forEach((a) => ancestorsOfMatch.add(a.id));
      n.children?.forEach((c) => collectAncestors(c as N, next));
    };
    collectAncestors(tree, []);

    const prune = (n: N): N | null => {
      const keep = matches.has(n.id) || ancestorsOfMatch.has(n.id) || n.id === tree.id;
      if (!keep) return null;
      const kids = (n.children ?? [])
        .map((c) => prune(c as N))
        .filter((c): c is N => c !== null);
      return { ...n, children: sortChildren(kids, filter, predicateMap) };
    };

    const sortAll = (n: N): N => ({
      ...n,
      children: n.children
        ? sortChildren(n.children.map((c) => sortAll(c as N)) as N[], filter, predicateMap)
        : undefined,
    });

    const finalTree = filter.mode === "hide"
      ? (prune(tree) ?? tree)
      : sortAll(tree);

    return {
      tree: finalTree,
      matches,
      stats: { total, matched: matches.size },
      allTags: [...allTagsSet].sort(),
    };
  }, [tree, filter, predicates]);
}
`;

/** Always-shipped shared engine files. */
export const generatedSharedTreeFiles: TreeRegistryFile[] = [
  {
    name: "TreeCanvas.tsx",
    path: "components/tree/TreeCanvas.tsx",
    code: components_tree_TreeCanvasRaw,
    language: "tsx",
    description: "Config-driven tree renderer — horizontal / vertical / radial / mindmap / org layouts, pan/zoom, inline editing, native pointer drag. Zero external deps.",
  },
  {
    name: "treeLayout.ts",
    path: "components/tree/treeLayout.ts",
    code: components_tree_treeLayoutRaw,
    language: "typescript",
    description: "Pure layout algorithms (horizontal, vertical, radial, mindmap, org).",
  },
  {
    name: "types.ts",
    path: "components/tree/types.ts",
    code: components_tree_typesRaw,
    language: "typescript",
    description: "Public types: TreeNode, TreeCanvasConfig, NodeRenderer, event payloads.",
  },
  {
    name: "graph/types.ts",
    path: "components/graph/types.ts",
    code: components_graph_typesRaw,
    language: "typescript",
    description: "GraphFilterState + GraphPredicate + NodeDataset contracts (shared with the toolbar).",
  },
];

/** Optional feature groups (e.g. the GraphToolbar) — installed only when a variant opts in. */
export const generatedOptionalTreeGroups: TreeOptionalGroup[] = [
  {
    feature: "toolbar",
    uiComponents: ["input","button","select"],
    npmDependencies: [],
    files: [
    {
      name: "graph/index.ts",
      path: "components/graph/index.ts",
      code: components_graph_indexRaw,
      language: "typescript",
      description: "Public surface for the search / sort / filter toolbar.",
    },
    {
      name: "graph/GraphToolbar.tsx",
      path: "components/graph/GraphToolbar.tsx",
      code: components_graph_GraphToolbarRaw,
      language: "tsx",
      description: "Search / sort / filter bar that overlays a TreeCanvas (config.showToolbar).",
    },
    {
      name: "graph/useGraphFilter.ts",
      path: "components/graph/useGraphFilter.ts",
      code: components_graph_useGraphFilterRaw,
      language: "typescript",
      description: "Hook that applies the toolbar's search/sort/filter to a tree.",
    },
    ],
  },
];
