#!/usr/bin/env node
/**
 * Embeds `app/components/ui/charts/*.tsx` into a single TS module so the chart
 * variant gallery can show full component source in the "Component" tab (no drift
 * vs the real `BarChart` / `AreaChart` implementations).
 *
 * Run: npm run build:chart-ui-lab-sources
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const CHARTS_DIR = path.join(ROOT, "app", "components", "ui", "charts");
const OUT = path.join(ROOT, "app", "components", "lab", "charts", "chartUiFullSourceGenerated.ts");

function main(): void {
  const names = fs
    .readdirSync(CHARTS_DIR)
    .filter((f) => f.endsWith(".tsx"))
    .sort((a, b) => a.localeCompare(b));

  const map: Record<string, string> = {};
  for (const file of names) {
    const key = file.replace(/\.tsx$/i, "");
    map[key] = fs.readFileSync(path.join(CHARTS_DIR, file), "utf8");
  }

  const serialized = JSON.stringify(map, null, 2);
  const banner = `/**\n * AUTO-GENERATED by scripts/embed-chart-ui-lab-sources.ts\n * DO NOT EDIT — run: npm run build:chart-ui-lab-sources\n */\n\n`;

  const body = `${banner}export const CHART_UI_FULL_SOURCE = ${serialized} as const;\n\nexport function getChartUiFullSource(importFile: string): string | undefined {\n  return (CHART_UI_FULL_SOURCE as Record<string, string>)[importFile];\n}\n`;

  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, body, "utf8");
  const kb = (fs.statSync(OUT).size / 1024).toFixed(1);
  console.log(`✅ chart UI lab sources: ${path.relative(ROOT, OUT)} (${kb} KB, ${names.length} files)`);
}

main();
